/**
 * Catalog of analyzer/tokenizer/normalizer names for the Analyze feature.
 *
 * Lists are sourced from Microsoft Learn documentation and kept as constants
 * so the UI can provide safe, discoverable dropdown options.
 */

// Lists are sourced from Microsoft Learn documentation for Azure AI Search.
// - Built-in analyzers, character filters, tokenizers, token filters:
//   https://learn.microsoft.com/azure/search/index-add-custom-analyzers
// - Language analyzers:
//   https://learn.microsoft.com/azure/search/index-add-language-analyzers
// - Normalizers:
//   https://learn.microsoft.com/azure/search/search-normalizers

export const ANALYZE_BUILT_IN_ANALYZERS = [
  'keyword',
  'pattern',
  'simple',
  // Docs show "standard" (also referred to as standard.lucene)
  'standard',
  'standard.lucene',
  'standardasciifolding.lucene',
  'stop',
  'whitespace',
] as const

export const ANALYZE_LANGUAGE_ANALYZERS = [
  // Ordered by language, and within each language: .microsoft -> .lucene
  'ar.microsoft',
  'ar.lucene',
  'bg.microsoft',
  'bg.lucene',
  'bn.microsoft',
  'ca.microsoft',
  'ca.lucene',
  'cs.microsoft',
  'cs.lucene',
  'da.microsoft',
  'da.lucene',
  'de.microsoft',
  'de.lucene',
  'el.microsoft',
  'el.lucene',
  'en.microsoft',
  'en.lucene',
  'es.microsoft',
  'es.lucene',
  'et.microsoft',
  'eu.lucene',
  'fa.lucene',
  'fi.microsoft',
  'fi.lucene',
  'fr.microsoft',
  'fr.lucene',
  'ga.lucene',
  'gl.lucene',
  'gu.microsoft',
  'he.microsoft',
  'hi.microsoft',
  'hi.lucene',
  'hr.microsoft',
  'hu.microsoft',
  'hu.lucene',
  'hy.lucene',
  'id.microsoft',
  'id.lucene',
  'is.microsoft',
  'it.microsoft',
  'it.lucene',
  'ja.microsoft',
  'ja.lucene',
  'kn.microsoft',
  'ko.microsoft',
  'ko.lucene',
  'lt.microsoft',
  'lv.microsoft',
  'lv.lucene',
  'ml.microsoft',
  'mr.microsoft',
  'ms.microsoft',
  'nb.microsoft',
  'nl.microsoft',
  'nl.lucene',
  'no.lucene',
  'pa.microsoft',
  'pl.microsoft',
  'pl.lucene',
  'pt-Br.microsoft',
  'pt-Br.lucene',
  'pt-Pt.microsoft',
  'pt-Pt.lucene',
  'ro.microsoft',
  'ro.lucene',
  'ru.microsoft',
  'ru.lucene',
  'sk.microsoft',
  'sl.microsoft',
  'sr-cyrillic.microsoft',
  'sr-latin.microsoft',
  'sv.microsoft',
  'sv.lucene',
  'ta.microsoft',
  'te.microsoft',
  'th.microsoft',
  'th.lucene',
  'tr.microsoft',
  'tr.lucene',
  'uk.microsoft',
  'ur.microsoft',
  'vi.microsoft',
  'zh-Hans.microsoft',
  'zh-Hans.lucene',
  'zh-Hant.microsoft',
  'zh-Hant.lucene',
] as const

export const ANALYZE_ANALYZERS = [
  ...ANALYZE_BUILT_IN_ANALYZERS,
  ...ANALYZE_LANGUAGE_ANALYZERS,
] as const

export const ANALYZE_CHAR_FILTERS = [
  'html_strip',
  'mapping',
  'pattern_replace',
] as const

export const ANALYZE_TOKENIZERS = [
  'classic',
  'edgeNGram',
  'keyword_v2',
  'letter',
  'lowercase',
  'microsoft_language_tokenizer',
  'microsoft_language_stemming_tokenizer',
  'nGram',
  'path_hierarchy_v2',
  'pattern',
  'standard_v2',
  'uax_url_email',
  'whitespace',
] as const

export const ANALYZE_TOKEN_FILTERS = [
  'arabic_normalization',
  'apostrophe',
  'asciifolding',
  'cjk_bigram',
  'cjk_width',
  'classic',
  'common_grams',
  'dictionary_decompounder',
  'edgeNGram_v2',
  'elision',
  'german_normalization',
  'hindi_normalization',
  'indic_normalization',
  'keep',
  'keyword_marker',
  'keyword_repeat',
  'kstem',
  'length',
  'limit',
  'lowercase',
  'nGram_v2',
  'pattern_capture',
  'pattern_replace',
  'persian_normalization',
  'phonetic',
  'porter_stem',
  'reverse',
  'scandinavian_normalization',
  'scandinavian_folding',
  'shingle',
  'snowball',
  'sorani_normalization',
  'stemmer',
  'stemmer_override',
  'stopwords',
  'synonym',
  'trim',
  'truncate',
  'unique',
  'uppercase',
  'word_delimiter',
] as const

export const ANALYZE_NORMALIZERS = [
  'standard',
  'lowercase',
  'uppercase',
  'asciifolding',
  'elision',
] as const
