import type { AutocompleteFormState, SearchFormState, SuggestFormState } from '../types'

export const DEFAULT_SEARCH_FORM: SearchFormState = {
  // These defaults are chosen to be usable out-of-the-box.
  search: '',
  queryType: 'simple',
  top: 10,
  skip: 0,
  count: true,
  select: '',
  filter: '',
  orderby: '',
  searchMode: '',
  searchFields: '',
  facets: '',
  highlight: '',
  scoringProfile: '',
  scoringParameters: '',
  queryRewrites: '',
  debug: '',
  semanticQuery: '',
  highlightPreTag: '',
  highlightPostTag: '',
  minimumCoverage: '',
  scoringStatistics: '',
  sessionId: '',
  speller: '',
  semanticErrorHandling: '',
  semanticMaxWaitInMilliseconds: '',
  semanticFields: '',
  vectorFilterMode: '',
  hybridMaxTextRecallSize: '',
  hybridCountAndFacetMode: '',
  semanticConfiguration: 'default',
  queryLanguage: 'ja-jp',
  captions: 'extractive',
  answers: 'extractive|count-3',
  vectorEnabled: false,
  vectorQueries: [],
  vectorKind: 'text',
  vectorText: '',
  vectorQueryRewrites: '',
  vector: '',
  vectorImageUrl: '',
  vectorBase64Image: '',
  vectorFields: '',
  vectorK: 10,
  vectorExhaustive: false,
  vectorWeight: 1.0,
  vectorThresholdKind: '',
  vectorThresholdValue: 0,
  vectorOversampling: '',
  vectorPerDocumentVectorLimit: '',
  vectorFilterOverride: '',
}

export const DEFAULT_AUTOCOMPLETE_FORM: AutocompleteFormState = {
  search: '',
  suggesterName: '',
  autocompleteMode: 'oneTermWithContext',
  searchFields: '',
  filter: '',
  top: 5,
  minimumCoverage: '',
  useFuzzyMatching: false,
  liveTest: true,
}

export const DEFAULT_SUGGEST_FORM: SuggestFormState = {
  search: '',
  suggesterName: '',
  searchFields: '',
  select: '',
  filter: '',
  orderby: '',
  top: 5,
  minimumCoverage: '',
  useFuzzyMatching: false,
  highlightPreTag: '<em>',
  highlightPostTag: '</em>',
  liveTest: true,
}
