/**
 * Feature Portal card definitions and guide data.
 *
 * Extracted into its own module so the guide drawer can render
 * at the AppLayout level (outside the Portal tab) and persist after
 * the user launches a feature.
 */

export type CardCategory = 'search' | 'builder' | 'optimization' | 'devtool' | 'experiment' | 'azure'

export type GuideStep = {
  icon: string
  titleJa: string
  titleEn: string
  descJa: string
  descEn: string
  /**
   * Optional CSS selector (e.g. `[data-guide-target="search-query"]`) that
   * identifies the UI element to highlight while this step is active in
   * companion mode. Unresolved selectors gracefully degrade (no highlight).
   */
  targetSelector?: string
}

export type FeatureGuide = {
  stepsJa: string
  stepsEn: string
  steps: GuideStep[]
  tipsJa?: string[]
  tipsEn?: string[]
  docsUrl?: string
}

export type PortalCard = {
  id: string
  icon: string
  isEmoji?: boolean
  category: CardCategory
  titleJa: string
  titleEn: string
  descJa: string
  descEn: string
  action?: string
  disabled?: boolean
  guide?: FeatureGuide
}

export const CATEGORY_ORDER: CardCategory[] = [
  'search',
  'builder',
  'optimization',
  'devtool',
  'experiment',
  'azure',
]

export const CATEGORY_META: Record<CardCategory, { labelJa: string; labelEn: string; iconClass: string }> = {
  search: { labelJa: '検索モード', labelEn: 'Search Modes', iconClass: 'bi-search' },
  builder: { labelJa: 'ビルダーツール', labelEn: 'Builder Tools', iconClass: 'bi-tools' },
  optimization: { labelJa: '最適化 & テスト', labelEn: 'Optimization & Testing', iconClass: 'bi-speedometer' },
  devtool: { labelJa: '開発者ツール', labelEn: 'Developer Tools', iconClass: 'bi-wrench-adjustable' },
  experiment: { labelJa: '実験管理', labelEn: 'Experiment Management', iconClass: 'bi-journal-bookmark' },
  azure: { labelJa: 'Azure AI Search 機能（未実装）', labelEn: 'Azure AI Search Features (Coming Soon)', iconClass: 'bi-cloud' },
}

export const PORTAL_CARDS: PortalCard[] = [
  // ── Search Modes ─────────────────────────────────────────────
  {
    id: 'fulltext-search',
    icon: 'search',
    category: 'search',
    titleJa: 'フルテキスト検索',
    titleEn: 'Full-Text Search',
    descJa: 'simple / full クエリ構文による全文検索。フィルター、ファセット、スコアリングプロファイルに対応。',
    descEn: 'Full-text search with simple / full query syntax. Supports filters, facets, and scoring profiles.',
    action: 'openQueryMode',
    guide: {
      stepsJa: 'フルテキスト検索の使い方',
      stepsEn: 'How to use Full-Text Search',
      steps: [
        { icon: 'plug', titleJa: '接続設定', titleEn: 'Configure Connection', descJa: 'Azure AI Search のエンドポイント (https://<service>.search.windows.net) と管理 API キー (またはクエリキー) を入力します。RAGOps Studio はクエリ実行に Search REST API を使うため、この情報が必須です。', descEn: 'Enter your Azure AI Search endpoint (https://<service>.search.windows.net) and admin (or query) API key. The Search REST API needs both to send requests.', targetSelector: '[data-guide-target="connection-section"]' },
        { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: 'ドロップダウンから検索対象インデックスを選択。Searchable=true のフィールドだけが BM25 のスコアリング対象になります。Index Inspector で属性を確認できます。', descEn: 'Pick the target index from the dropdown. Only fields with Searchable=true contribute to BM25 scoring. Use Index Inspector to verify attributes.', targetSelector: '[data-guide-target="index-dropdown"]' },
        { icon: 'pencil-square', titleJa: 'search パラメータ入力', titleEn: 'Enter the search parameter', descJa: 'search フィールドにクエリ文字列を入力。空文字や "*" は全件検索 (match-all) になります。スペース区切りの語は OR 結合 (simple) または queryType に応じて Lucene 構文で解釈されます。', descEn: 'Type into the search field. Empty string or "*" runs a match-all query. Space-separated terms are OR-combined (simple) or parsed via Lucene syntax depending on queryType.', targetSelector: '[data-guide-target="search-query"]' },
        { icon: 'gear', titleJa: 'queryType を選ぶ', titleEn: 'Choose queryType', descJa: 'simple は + (AND), | (OR), - (NOT), "" (フレーズ), * (サフィックス), ( ) (グループ化) をサポート。full は Lucene 構文を解放し、ワイルドカード/正規表現/曖昧/近接/フィールド指定/ブースト ^ などが使えます。意図せず構文エラーが出やすいので simple から始めるのが安全です。', descEn: 'simple supports + (AND), | (OR), - (NOT), "" (phrase), * (suffix), ( ) grouping. full unlocks Lucene syntax: wildcards, regex, fuzzy, proximity, field-scoped, ^boost. simple is safer; switch to full only when you need those features.', targetSelector: '[data-guide-target="query-type"]' },
        { icon: 'funnel', titleJa: 'filter で絞り込み', titleEn: 'Refine with filter', descJa: 'filter は OData 式で、Filterable=true のフィールドにのみ適用可能 (BM25 とは別系統で AND 結合)。例: category eq \'docs\' and price lt 100。Filter Builder で GUI 構築できます。', descEn: 'filter is an OData expression and works only on Filterable=true fields (independent of BM25 and AND-combined). Example: category eq \'docs\' and price lt 100. Use Filter Builder for a GUI experience.' },
        { icon: 'sliders', titleJa: 'searchFields / searchMode', titleEn: 'searchFields / searchMode', descJa: 'searchFields でスコアリング対象フィールドを限定 (例: title,body)。searchMode=any (既定) は 1 つでも一致でヒット、all は全語一致が必要。タイトルだけにマッチを偏らせたいときに有効。', descEn: 'searchFields restricts scoring to specific fields (e.g. title,body). searchMode=any (default) returns docs matching any term; all requires every term to match. Useful when you want title-only matches to dominate.' },
        { icon: 'eye', titleJa: 'select / $top / $skip / $count', titleEn: 'select / $top / $skip / $count', descJa: 'select で返すフィールドを指定するとレスポンスが軽くなります。$top で最大返却件数 (既定 50, 最大 1000)、$skip でページング、$count=true でヒット総数を取得できます。', descEn: 'select limits returned fields for lighter payloads. $top sets max results (default 50, max 1000), $skip paginates, $count=true returns total hit count.' },
        { icon: 'bar-chart', titleJa: 'facets / scoringProfile (任意)', titleEn: 'facets / scoringProfile (optional)', descJa: 'facets でカテゴリ別件数を集計 (Facetable=true 必須)。scoringProfile を指定するとインデックスに定義した重み付け関数 (新しさ・距離・タグマッチ等) を適用できます。', descEn: 'facets aggregate counts by category (requires Facetable=true). scoringProfile applies index-defined weighting functions (freshness, distance, tag boost, etc.).' },
        { icon: 'play-circle', titleJa: '実行 & スコア確認', titleEn: 'Execute & inspect score', descJa: 'Execute を押すと右ペインに JSON が出ます。@search.score が BM25 スコアです (相対比較用、絶対値に意味はありません)。Request タブで送った body を確認できます。', descEn: 'Click Execute and inspect the JSON in the right pane. @search.score is the BM25 score (only meaningful for relative comparison). The Request tab shows the body you actually sent.', targetSelector: '[data-guide-target="execute-button"]' },
      ],
      tipsJa: [
        'BM25 スコアはインデックス内の語の希少性 (IDF) と文書内頻度 (TF)、フィールド長などから計算され、絶対値の大小は他クエリと比較しても意味がありません。同一クエリ内での順位比較に使ってください。',
        '日本語フィールドは ja.lucene / ja.microsoft アナライザーを設定しないと意図したトークン分割になりません。Analyze API で実際の分割結果を確認するのがおすすめです。',
        'queryType=full でワイルドカードや fuzzy (term~) を使うとリコールは上がりますが、IDF が下がってスコアが薄まることがあります。',
        'highlight パラメータでヒット箇所のスニペット (em タグ) を取得できます。表示用に便利。',
        'searchMode=all は AND 検索相当で精度重視、any は OR 検索相当でリコール重視と覚えると使い分けやすいです。',
        'orderby を指定すると BM25 スコアではなく明示順序になります (例: price desc)。「人気順」など UX 上の固定ソートに使います。',
      ],
      tipsEn: [
        'BM25 scores depend on term rarity (IDF), in-document frequency (TF), and field length within this index. Absolute values are NOT comparable across queries — only ranks matter.',
        'For Japanese fields, set ja.lucene / ja.microsoft analyzers, otherwise tokenization may not match user intent. Use Analyze API to inspect actual tokens.',
        'queryType=full with wildcards or fuzzy (term~) increases recall but tends to dilute scores via lower IDF.',
        'Use the highlight parameter to get snippets with em tags around matching terms — handy for UI rendering.',
        'searchMode=all ≈ AND (precision), searchMode=any ≈ OR (recall). Easy mnemonic when tuning.',
        'orderby overrides BM25 ordering with an explicit sort (e.g. price desc). Use it for fixed-order UX like "newest first".',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-query-overview',
    },
  },
  {
    id: 'semantic-search',
    icon: 'stars',
    category: 'search',
    titleJa: 'セマンティック検索',
    titleEn: 'Semantic Search',
    descJa: 'Bing 由来の深層学習モデルによるセマンティックランキング。キャプションとアンサーの生成。',
    descEn: 'Semantic ranking with deep learning models from Bing. Generates captions and answers.',
    action: 'openSemanticVectorMode',
    guide: {
      stepsJa: 'セマンティック検索の使い方',
      stepsEn: 'How to use Semantic Search',
      steps: [
        { icon: 'toggles', titleJa: 'Semantic-Vector モード', titleEn: 'Semantic-Vector Mode', descJa: 'Lab Mode を Semantic-Vector に切り替えます。queryType=semantic を指定できる UI が出現します。', descEn: 'Switch Lab Mode to Semantic-Vector. The UI for queryType=semantic becomes available.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
        { icon: 'shield-check', titleJa: 'サービス側の前提条件', titleEn: 'Service prerequisites', descJa: 'Semantic ranker は Free 以外 (Basic 以上) の SKU で「Semantic ranker」設定を有効にしている必要があります。利用しているサービスで未有効ならポータルから有効化してください (有料機能)。', descEn: 'Semantic ranker requires a Basic or higher SKU with the “Semantic ranker” feature turned on for the service. Enable it from the Azure portal if it is currently off (billable feature).' },
        { icon: 'list-ul', titleJa: 'セマンティック構成を持つインデックス', titleEn: 'Index with semantic configuration', descJa: 'インデックス定義に semantic.configurations が必要。titleField / contentFields / keywordsFields のマッピングがリランカーへの入力になります。Index Inspector で確認可能。', descEn: 'The index needs semantic.configurations defined. titleField / contentFields / keywordsFields are the inputs to the reranker. Check via Index Inspector.', targetSelector: '[data-guide-target="index-dropdown"]' },
        { icon: 'pencil-square', titleJa: '自然言語クエリを入力', titleEn: 'Enter a natural-language query', descJa: 'セマンティックランカーは「質問らしい」自然文に強いです。"how to reset password" のような問いの形が効果的。短すぎるキーワードでは BM25 とほぼ同じ結果になります。', descEn: 'The semantic ranker shines on question-like natural text (e.g. "how to reset password"). Single keywords yield results similar to plain BM25.', targetSelector: '[data-guide-target="search-query"]' },
        { icon: 'gear', titleJa: 'queryType=semantic と semanticConfiguration', titleEn: 'queryType=semantic & semanticConfiguration', descJa: 'queryType を semantic に切り替え、使用する semanticConfiguration 名を指定します。queryLanguage は対象言語 (例: ja-JP, en-US) を入れると captions/answers の品質が上がります。', descEn: 'Set queryType to semantic and pick a semanticConfiguration name. queryLanguage (e.g. ja-JP, en-US) improves captions/answers quality.', targetSelector: '[data-guide-target="query-type"]' },
        { icon: 'chat-quote', titleJa: 'captions を有効化', titleEn: 'Enable captions', descJa: 'captions=extractive を指定するとヒット文書から抜粋スニペットが返ります (highlights=true でハイライト付き)。回答 UI に貼るだけで使える要約として便利。', descEn: 'Set captions=extractive to receive snippet excerpts from each result (with highlights=true for marked spans). Drop-in summaries for answer UIs.' },
        { icon: 'question-circle', titleJa: 'answers を有効化 (任意)', titleEn: 'Enable answers (optional)', descJa: 'answers=extractive|count-3 のように指定すると、回答候補となる文を上位文書から抽出します。質問形クエリで効果的。生成 AI ではなく抽出型なので根拠が文書内にあります。', descEn: 'answers=extractive|count-3 extracts candidate answer sentences from top documents. Effective for question-shaped queries; extractive (not generative), so the answer is grounded in the source.' },
        { icon: 'sliders', titleJa: 'semanticMaxWaitInMilliseconds', titleEn: 'semanticMaxWaitInMilliseconds', descJa: 'リランカーの最大待機時間 (ミリ秒) を指定可能。タイムアウト時は @search.semanticPartialResponseReason に理由が入ります。', descEn: 'Sets max wait time (ms) for the reranker. On timeout, @search.semanticPartialResponseReason contains the cause.' },
        { icon: 'play-circle', titleJa: '実行 & rerankerScore 確認', titleEn: 'Execute & inspect rerankerScore', descJa: 'Execute 後、各文書の @search.rerankerScore (0〜4 程度) がリランカーのスコアです。元の @search.score (BM25) も並列に返ります。順位逆転を見比べると効果が分かります。', descEn: 'After Execute, @search.rerankerScore (≈0–4) is the reranker score. The original @search.score (BM25) is also returned. Compare ordering changes to see the impact.', targetSelector: '[data-guide-target="execute-button"]' },
      ],
      tipsJa: [
        'リランカーは BM25 上位最大 50 件のみを再評価します。BM25 でそもそも上位に入らない文書は救えないため、リコール改善はハイブリッド検索や synonym map で行うのが定石。',
        '@search.rerankerScore は BM25 スコアと尺度が異なります。混ぜて並べ替えるのではなく、リランカー有効時はリランカースコア順を採用するのが正解。',
        'queryLanguage は captions/answers の言語処理に効きます。日本語クエリなら ja-JP を必ず指定。',
        'semanticConfiguration の titleField/contentFields のマッピングが品質を左右します。本文に当たるフィールドは contentFields に、人手要約は keywordsFields に入れると効果的。',
        'debug=semantic を指定するとリランカー入力 (タイトル/本文の抽出結果) を確認でき、スコアリングがおかしいときの調査に使えます。',
        'リランカーは課金対象 (1000 クエリあたり)。本番では QPS と相談してキャッシュやハイブリッド検索との併用を検討してください。',
      ],
      tipsEn: [
        'The reranker only re-scores the top 50 BM25 results. Documents that BM25 missed cannot be recovered — improve recall via hybrid search or synonym maps instead.',
        '@search.rerankerScore lives on a different scale than BM25. When the reranker is enabled, sort by rerankerScore rather than mixing the two.',
        'queryLanguage drives caption/answer language processing. Always set ja-JP for Japanese queries.',
        'Quality depends on the titleField/contentFields mapping in semanticConfiguration. Put body text into contentFields and human-curated keywords into keywordsFields.',
        'debug=semantic exposes the reranker’s actual inputs (extracted title/content), which is invaluable for diagnosing odd scores.',
        'Reranker is billed per 1,000 queries. In production, consider caching and combining with hybrid search to control cost at high QPS.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/semantic-how-to-query-request',
    },
  },
  {
    id: 'vector-search',
    icon: 'diagram-3',
    category: 'search',
    titleJa: 'ベクトル検索',
    titleEn: 'Vector Search',
    descJa: 'テキスト / 画像のベクトルクエリ。HNSW / KNN アルゴリズム、フィルター付きベクトル検索に対応。',
    descEn: 'Vector queries for text / image. Supports HNSW / KNN algorithms with filtered vector search.',
    action: 'openSemanticVectorMode',
    guide: {
      stepsJa: 'ベクトル検索の使い方',
      stepsEn: 'How to use Vector Search',
      steps: [
        { icon: 'toggles', titleJa: 'Semantic-Vector モード', titleEn: 'Semantic-Vector Mode', descJa: 'Lab Mode を Semantic-Vector に切り替えます。これがベクトル検索を実行するための入口です。', descEn: 'Switch Lab Mode to Semantic-Vector. This is the entry point for vector search.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
        { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: 'Collection(Edm.Single) のベクトルフィールド (例: contentVector) と vectorSearch プロファイルを持つインデックスを選びます。', descEn: 'Select an index that contains vector fields (Collection(Edm.Single)) bound to a vectorSearch profile.', targetSelector: '[data-guide-target="index-dropdown"]' },
        { icon: 'toggle-on', titleJa: 'vectorQueries を有効化', titleEn: 'Enable vectorQueries', descJa: 'vectorQueries を on に切り替えると、ベクトル検索の入力フォームが展開されます。off の場合はリクエストに vectorQueries 配列が含まれません。', descEn: 'Toggle vectorQueries to on to expand the vector query form. When off, no vectorQueries array is sent in the request.', targetSelector: '[data-guide-target="vector-toggle"]' },
        { icon: 'braces', titleJa: 'vectorQueries とは', titleEn: 'About vectorQueries', descJa: 'vectorQueries は配列で、1 件以上のベクトルクエリを並列実行できます。各要素は { kind, fields, k, …入力 } の形。kind に "text" / "vector" / "imageUrl" / "imageBinary" を指定します。fields は検索対象のベクトルフィールド名 (カンマ区切りで複数可)、k は返す近傍件数です。', descEn: 'vectorQueries is an array — you can submit multiple vector queries in parallel. Each item has the shape { kind, fields, k, …input }. kind is "text" / "vector" / "imageUrl" / "imageBinary"; fields lists the target vector field(s) (comma-separated); k is the number of nearest neighbors to return.', targetSelector: '[data-guide-target="vector-section"]' },
        { icon: 'tag', titleJa: 'vector.kind を選ぶ', titleEn: 'Choose vector.kind', descJa: '"text" は Azure 側のベクタライザーでテキストを自動ベクトル化 (統合ベクトル化)。"vector" は自分で計算した埋め込み配列を渡す方式。"imageUrl" / "imageBinary" は画像クエリ用 (AI Vision など)。', descEn: '"text" relies on the index vectorizer to embed your text (integrated vectorization). "vector" lets you supply a precomputed embedding array. "imageUrl" / "imageBinary" are for image queries (e.g. AI Vision).', targetSelector: '[data-guide-target="vector-kind"]' },
        { icon: 'collection', titleJa: 'vector.fields を指定', titleEn: 'Set vector.fields', descJa: 'クエリベクトルと同じ次元数・同じ埋め込みモデルで作成されたベクトルフィールドを指定します (異なるモデル同士は混在不可)。複数指定するとマルチベクトル検索になります。', descEn: 'Specify a vector field built with the same dimensionality and embedding model as your query vector (do not mix models). Multiple fields perform multi-vector search.', targetSelector: '[data-guide-target="vector-fields"]' },
        { icon: 'sliders', titleJa: 'vector.k を設定', titleEn: 'Set vector.k', descJa: 'k は HNSW で取り出す近傍件数 (例: 50)。最終的な top スコアは k と $top の小さい方になります。大きくすると recall が上がる代わりにレイテンシも増えます。', descEn: 'k is the number of neighbors HNSW returns (e.g. 50); the final top results are min(k, $top). Larger k → higher recall but more latency.', targetSelector: '[data-guide-target="vector-k"]' },
        { icon: 'input-cursor-text', titleJa: '入力 A: text を渡す', titleEn: 'Input A: pass text', descJa: 'kind=text の場合、vector.text に自然言語クエリを入力します。インデックスに登録された vectorizer が自動でクエリをベクトル化してくれるため、クライアント側で埋め込みモデルを呼ぶ必要がありません。', descEn: 'If kind=text, type your natural-language query into vector.text. The vectorizer attached to the field embeds the query for you — no client-side embedding call needed.', targetSelector: '[data-guide-target="vector-input"]' },
        { icon: 'code-square', titleJa: '入力 B: 事前計算済み vector を渡す', titleEn: 'Input B: pass a precomputed vector', descJa: 'kind=vector の場合、vector フィールドに埋め込み配列をカンマ区切りで貼り付けます (例: 0.12, -0.04, 0.83, …)。配列の長さはターゲットフィールドの dimensions と完全一致させ、必ずインデックス側と同じ埋め込みモデルで生成してください。Tools > Text to Vector で簡単に生成できます。', descEn: 'If kind=vector, paste the embedding array as comma-separated floats into the vector field (e.g. 0.12, -0.04, 0.83, …). The array length must exactly match the target field’s dimensions and be produced by the same embedding model as the index. Use Tools > Text to Vector to generate one quickly.', targetSelector: '[data-guide-target="vector-input"]' },
        { icon: 'plus-circle', titleJa: '複数クエリを追加 (任意)', titleEn: 'Add multiple queries (optional)', descJa: '"vectorQueries に追加" を押すと現在の設定を 1 件として登録し、kind や fields を変えてさらに追加できます。複数件は AI Search 内部で RRF により融合されます。', descEn: 'Click “Add to vectorQueries” to commit the current settings as one entry, then add more with different kind/fields. Multiple entries are fused internally with RRF.', targetSelector: '[data-guide-target="vector-add"]' },
        { icon: 'play-circle', titleJa: '実行 & 結果確認', titleEn: 'Execute & inspect results', descJa: 'Execute を押して実行し、@search.score (純粋ベクトル検索ではコサイン類似度由来) を確認します。Request タブで送信した JSON の vectorQueries 配列を見直すと挙動の理解が深まります。', descEn: 'Click Execute and inspect @search.score (derived from cosine similarity for pure vector search). Open the Request tab to review the vectorQueries array you actually sent.', targetSelector: '[data-guide-target="execute-button"]' },
      ],
      tipsJa: [
        'vectorQueries は配列です。fields/kind の組合せを変えて複数追加すると、1 リクエストでマルチベクトル検索を行えます (内部で RRF 融合)。',
        '事前計算済みベクトルを使う場合 (kind=vector)、配列次元数とインデックス側 dimensions を必ず一致させ、同じ埋め込みモデル (例: text-embedding-3-large) で生成してください。次元不一致や別モデル由来のベクトルはエラーまたは無意味な結果になります。',
        'top-level の search フィールドにテキストを入れるとハイブリッド検索 (BM25 + ベクトル) に自動切替されます。純粋なベクトル検索を行いたいときは search を空のままにします。',
        'k は内部の HNSW 候補数。大きくすると recall が上がりますがレイテンシも増えます。50〜100 から始めて調整するのが目安。',
        'exhaustive=true (vectorExhaustive) は HNSW を使わず全件 (brute force KNN) で計算します。再現率の上限を測定したいときに有効ですが、本番では高コスト。',
        'filter を併用するとベクトル空間で k 件取った後にフィルタ適用ではなく、AI Search が pre-filter / post-filter モードで賢く処理します (vectorFilterMode を参照)。',
        'クエリの埋め込みは Tools > Text to Vector で簡単に生成できます。生成した配列をそのまま vector フィールドへ貼り付け可能。',
      ],
      tipsEn: [
        'vectorQueries is an array. Add multiple entries with different fields/kind to perform multi-vector search in a single request (fused internally via RRF).',
        'When passing a precomputed vector (kind=vector), the array length must match the field’s dimensions and be produced by the same embedding model as the index (e.g. text-embedding-3-large). Mismatches cause errors or meaningless scores.',
        'Putting text in the top-level search field automatically turns this into hybrid search (BM25 + vector). Leave search empty for pure vector search.',
        'k is the HNSW candidate count. Larger k → higher recall but more latency. Start at 50–100 and tune.',
        'exhaustive=true (vectorExhaustive) skips HNSW and runs brute-force KNN over all docs. Useful for measuring recall ceilings, but expensive in production.',
        'Combining filter with vector queries is handled smartly via pre/post-filter modes (see vectorFilterMode) rather than naively filtering after the k cutoff.',
        'Generate query embeddings quickly via Tools > Text to Vector and paste the array straight into the vector field.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/vector-search-how-to-query',
    },
  },
  {
    id: 'hybrid-search',
    icon: 'intersect',
    category: 'search',
    titleJa: 'ハイブリッド検索',
    titleEn: 'Hybrid Search',
    descJa: 'テキスト検索とベクトル検索を RRF (Reciprocal Rank Fusion) で統合。maxTextRecallSize で調整可能。',
    descEn: 'Combines text and vector search using RRF (Reciprocal Rank Fusion). Tunable via maxTextRecallSize.',
    action: 'openSemanticVectorMode',
    guide: {
      stepsJa: 'ハイブリッド検索の使い方',
      stepsEn: 'How to use Hybrid Search',
      steps: [
        { icon: 'toggles', titleJa: 'Semantic-Vector モード', titleEn: 'Semantic-Vector Mode', descJa: 'Lab Mode を Semantic-Vector に切り替えます。1 リクエスト内で search と vectorQueries を同時に送るのがハイブリッド検索の本質です。', descEn: 'Switch to Semantic-Vector mode. Hybrid search means sending search and vectorQueries together in one request.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
        { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: 'Searchable=true のテキストフィールドと、ベクトルフィールド (Collection(Edm.Single) + vectorSearch プロファイル) の両方を持つインデックスを選びます。', descEn: 'Pick an index that has both Searchable=true text fields and vector fields (Collection(Edm.Single) bound to a vectorSearch profile).', targetSelector: '[data-guide-target="index-dropdown"]' },
        { icon: 'pencil-square', titleJa: 'search にテキストを入れる', titleEn: 'Put text in search', descJa: 'search フィールドにキーワードを入れることが「BM25 側を発火させる」スイッチです。空のままだとピュアベクトル検索のままになります。', descEn: 'Filling the search field is what activates the BM25 side. Leaving it empty keeps the request as a pure vector search.', targetSelector: '[data-guide-target="search-query"]' },
        { icon: 'toggle-on', titleJa: 'vectorQueries を有効化', titleEn: 'Enable vectorQueries', descJa: 'vectorQueries=on にして 1 件以上のベクトルクエリ (kind/fields/k/入力) を追加します。詳細はベクトル検索カードを参照。', descEn: 'Turn vectorQueries on and add at least one entry (kind/fields/k/input). See the Vector Search card for details.', targetSelector: '[data-guide-target="vector-toggle"]' },
        { icon: 'sliders', titleJa: 'vectorWeight で重み調整', titleEn: 'Tune vectorWeight', descJa: 'vector.weight (既定 1.0) は RRF 融合時のベクトル側ランクの重み。1.0 で同等、>1 でベクトル寄り、<1 でテキスト寄り。0.5〜2.0 の範囲で実験するのが一般的。', descEn: 'vector.weight (default 1.0) scales the vector ranks during RRF fusion. =1 equal, >1 favors vector, <1 favors text. Typical range to explore: 0.5–2.0.' },
        { icon: 'arrow-down-up', titleJa: 'maxTextRecallSize / hybridSearch', titleEn: 'maxTextRecallSize / hybridSearch', descJa: 'hybridSearch.maxTextRecallSize で BM25 側の候補数 (既定 1000) を制御できます。BM25 のリコールが過剰でベクトルランクが薄まるときに小さく、その逆で大きくします。', descEn: 'hybridSearch.maxTextRecallSize controls the BM25 candidate pool (default 1000). Lower it when BM25 recall drowns out vector ranks; raise it for the opposite.' },
        { icon: 'stars', titleJa: 'queryType=semantic で semantic_hybrid', titleEn: 'queryType=semantic → semantic_hybrid', descJa: 'queryType を semantic にすると RRF 融合後の上位がリランカーで再評価されます (semantic_hybrid)。多くのワークロードで最も高品質なモード。', descEn: 'Setting queryType=semantic re-scores the top RRF results with the semantic reranker (semantic_hybrid). Often the highest-quality mode for production workloads.', targetSelector: '[data-guide-target="query-type"]' },
        { icon: 'play-circle', titleJa: '実行 & RRF スコア確認', titleEn: 'Execute & inspect RRF score', descJa: 'Execute すると @search.score が RRF 融合後スコアで返ります (BM25 でも純ベクトルでもない別尺度)。Request タブで送った body を再確認するとパラメータの効きが分かります。', descEn: 'After Execute, @search.score is the post-RRF fused score (different scale from BM25 or pure vector). Open the Request tab to verify which parameters were sent.', targetSelector: '[data-guide-target="execute-button"]' },
        { icon: 'columns-gap', titleJa: 'All Modes で 4 モード比較', titleEn: 'All Modes — 4-way comparison', descJa: 'All Modes 実行を使うと query / vector / hybrid / semantic_hybrid の 4 つを一括で投げて結果を並列比較できます。チューニングの初手として有用。', descEn: 'Use All Modes to dispatch query / vector / hybrid / semantic_hybrid in parallel and compare side by side. Great as a first tuning step.' },
      ],
      tipsJa: [
        'RRF は順位ベース融合 (1/(k+rank)) なので、各サブクエリのスコア絶対値の違いに左右されません。BM25 とベクトルのスコア尺度が違っても安全に統合できます。',
        'ピュアハイブリッド検索 (semantic 無し) でも、純粋なベクトル検索やキーワード検索より大幅に品質が上がるケースが多いです (Microsoft の公式評価でも RRF ハイブリッドが堅調)。',
        '本番では semantic_hybrid (queryType=semantic) を採用し、最終ランキングは @search.rerankerScore を使うのが多くのケースで最適。',
        'ハイブリッド検索でも filter は引き続き OData 式で適用可能。recall を絞りすぎないよう vectorFilterMode (preFilter / postFilter) を確認してください。',
        'maxTextRecallSize を変えるとリランカー対象も変わります。BM25 候補が少なすぎるとリランカーで救えるドキュメントも消えるので注意。',
        'top-level の search を空にしたまま vectorQueries だけを有効にした状態は「ピュアベクトル検索」であり、ハイブリッドではありません。',
      ],
      tipsEn: [
        'RRF is rank-based fusion (1/(k+rank)) and therefore robust to different score scales — BM25 and vector scores can be combined safely without normalization.',
        'Pure hybrid (without semantic) often beats both pure vector and pure keyword search — Microsoft’s own evaluations show RRF hybrid is consistently strong.',
        'In production, semantic_hybrid (queryType=semantic) is usually the best default; sort the final ranking by @search.rerankerScore.',
        'filter (OData) still applies in hybrid mode. Watch vectorFilterMode (preFilter / postFilter) so you do not over-prune recall.',
        'Changing maxTextRecallSize also changes what the reranker sees. Too few BM25 candidates = lost recoverable docs.',
        'Empty search + vectorQueries on is pure vector search, NOT hybrid. Make sure search has text to enable hybrid behavior.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/hybrid-search-how-to-query',
    },
  },
  {
    id: 'agentic-retrieval',
    icon: 'robot',
    category: 'search',
    titleJa: 'Agentic Retrieval',
    titleEn: 'Agentic Retrieval',
    descJa: 'Knowledge Base / Knowledge Source を使ったエージェント型検索。アクティビティタイムライン可視化。',
    descEn: 'Agent-based retrieval using Knowledge Base / Source. Activity timeline visualization.',
    action: 'openAgenticMode',
    guide: {
      stepsJa: 'Agentic Retrieval の使い方',
      stepsEn: 'How to use Agentic Retrieval',
      steps: [
        { icon: 'shield-check', titleJa: '前提条件', titleEn: 'Prerequisites', descJa: '事前に (1) Knowledge Source Builder で 1 つ以上のソースを公開、(2) Knowledge Base Builder でそれらを束ねた Knowledge Base を公開、(3) Azure OpenAI モデル (例: gpt-4o-mini) のデプロイメントとロール割り当てが必要です。', descEn: 'You first need (1) one or more Knowledge Sources published via Knowledge Source Builder, (2) a Knowledge Base bundling them via Knowledge Base Builder, and (3) an Azure OpenAI deployment (e.g. gpt-4o-mini) with proper role assignments.' },
        { icon: 'toggles', titleJa: 'Agentic モード', titleEn: 'Agentic Mode', descJa: 'Lab Mode を Agentic に切り替えます。API バージョンは自動で preview (現状 2025-08-01-preview 系) に切り替わります。GA API では使えません。', descEn: 'Switch Lab Mode to Agentic. The API version auto-switches to preview (currently the 2025-08-01-preview family). Not available in GA APIs.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
        { icon: 'database', titleJa: 'Knowledge Base 選択', titleEn: 'Select Knowledge Base', descJa: 'ドロップダウンから対象の Knowledge Base を選びます。配下の Knowledge Sources のうち Agent がクエリ意図に応じて 1 つ以上を選択して検索します。', descEn: 'Pick the target Knowledge Base. The Agent will select one or more of its Knowledge Sources based on the query intent and run them.', targetSelector: '[data-guide-target="knowledge-base-dropdown"]' },
        { icon: 'chat-dots', titleJa: 'メッセージを構築', titleEn: 'Compose messages', descJa: 'messages 配列で system/user の対話履歴を組み立てます。Agent はこの履歴を読んでサブクエリ計画 (1〜数件の query) を立てるため、文脈を残すほど結果が安定します。', descEn: 'Build a messages array of system/user turns. The Agent reads this history to plan subqueries (typically a handful) — keeping context yields more stable results.', targetSelector: '[data-guide-target="agentic-messages"]' },
        { icon: 'cpu', titleJa: 'retrievalReasoningEffort', titleEn: 'retrievalReasoningEffort', descJa: 'low / medium / high で計画の深さを切り替えます。high は分解されるサブクエリ数とトークン消費が増える代わりに広く拾えます。コスト/レイテンシと品質のトレードオフ。', descEn: 'low / medium / high tunes plan depth. high produces more subqueries and uses more tokens but achieves broader recall — a quality vs. cost/latency trade-off.' },
        { icon: 'sliders', titleJa: 'maxOutputSize / outputFormat', titleEn: 'maxOutputSize / outputFormat', descJa: '応答テキストの最大トークン数や、回答の形式 (text / answerSynthesis) を指定。answerSynthesis は引用付きの最終回答を生成します。', descEn: 'Set the response token cap and outputFormat (text / answerSynthesis). answerSynthesis produces a final grounded answer with citations.' },
        { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: 'Execute を押すと内部で「サブクエリ計画 → 各 Knowledge Source 並列検索 → 結果集約 → 最終応答合成」のパイプラインが走ります。', descEn: 'Clicking Execute runs the pipeline: plan subqueries → fan out to each Knowledge Source in parallel → aggregate → synthesize the final response.', targetSelector: '[data-guide-target="execute-button"]' },
        { icon: 'list-task', titleJa: 'Activity タイムライン確認', titleEn: 'Inspect the Activity timeline', descJa: '結果ペインの Activity タブで、Agent が実際に発行したサブクエリ、各ソースの実行時間、入出力トークン数、選択ソースを時系列で確認できます。チューニングの最初の手掛かり。', descEn: 'In the Activity tab you can see the actual subqueries issued, per-source execution time, token I/O, and which sources were chosen — your first stop for tuning.' },
        { icon: 'bookmark-check', titleJa: 'References 確認', titleEn: 'Inspect References', descJa: 'References タブで最終応答が引用した文書チャンクを一覧できます。RAG の根拠表示にそのまま使えます。', descEn: 'The References tab lists the document chunks cited by the final response — drop-in grounding evidence for RAG UIs.' },
      ],
      tipsJa: [
        'Knowledge Base / Knowledge Source は preview API 専用機能です。GA API バージョンに切り替えると一覧が空になるので注意。',
        '複数 Knowledge Source を 1 つの Knowledge Base に束ねると、Agent が「どのソースを使うべきか」を自律判断します。ソースは目的別 (FAQ / マニュアル / 会議録など) に分けるのが効果的。',
        'retrievalReasoningEffort=high は強力ですが課金トークンと latency が大きく増えます。本番は medium スタートで A/B するのが目安。',
        'メッセージに system プロンプトで「専門領域」「禁止事項」「回答形式」を明記すると、サブクエリ計画と最終回答の両方が安定します。',
        'outputFormat=answerSynthesis は LLM が生成する文ですが、必ず References に列挙された範囲から書かれます (グラウンディング)。',
        'Activity タブを見ながら「想定したソースが選ばれていない」ときは、Knowledge Source の description / 名称をユースケースに沿って書き直すと選択精度が上がります。',
      ],
      tipsEn: [
        'Knowledge Base / Knowledge Source are preview-only constructs. Switching to a GA API version makes the dropdowns empty.',
        'Bundling multiple Knowledge Sources in one Knowledge Base lets the Agent autonomously choose which to query. Split sources by purpose (FAQ / manuals / meeting notes…).',
        'retrievalReasoningEffort=high is powerful but materially increases tokens and latency. Start at medium in production and A/B from there.',
        'A clear system prompt (domain, do/don’t, format) stabilizes both subquery planning and the final answer.',
        'outputFormat=answerSynthesis is LLM-generated but stays grounded — content is constrained to the cited References.',
        'If the Activity timeline shows the wrong sources being chosen, rewrite each Knowledge Source description/name to match its actual use case.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-agentic-retrieval-how-to-retrieve',
    },
  },
  {
    id: 'analyze-api',
    icon: 'eyedropper',
    category: 'search',
    titleJa: 'テキスト分析 (Analyze API)',
    titleEn: 'Text Analysis (Analyze API)',
    descJa: 'アナライザー、トークナイザー、文字フィルター、トークンフィルターの動作を確認。',
    descEn: 'Test analyzers, tokenizers, char filters, and token filters interactively.',
    action: 'openAnalyzeMode',
    guide: {
      stepsJa: 'テキスト分析の使い方',
      stepsEn: 'How to use Text Analysis',
      steps: [
        { icon: 'toggles', titleJa: 'Analyze モード', titleEn: 'Analyze Mode', descJa: 'Lab Mode を Analyze に切り替えます。これは Search REST API の Analyze Text エンドポイント (POST /indexes/{name}/analyze) を呼び出すモードです。', descEn: 'Switch Lab Mode to Analyze. This mode calls the Analyze Text REST endpoint (POST /indexes/{name}/analyze).', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
        { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: 'Analyze API はインデックス単位で実行されるため、対象インデックスを選びます (定義済みアナライザーや customAnalyzers の解決に使われます)。', descEn: 'The Analyze API is index-scoped, so select the target index (used to resolve built-in analyzers and any customAnalyzers).', targetSelector: '[data-guide-target="index-dropdown"]' },
        { icon: 'input-cursor-text', titleJa: 'text を入力', titleEn: 'Enter text', descJa: '分析したい文字列を text に入力します。長文を入れて URL/英数字混在/絵文字などのトークン化挙動を確認するのが効果的。', descEn: 'Type the string to analyze into text. Longer text helps reveal how URLs, mixed alphanumerics, or emojis are tokenized.', targetSelector: '[data-guide-target="analyze-text"]' },
        { icon: 'gear', titleJa: 'analyzer を指定 (パターン A)', titleEn: 'Specify analyzer (option A)', descJa: 'analyzer に組み込みアナライザー名 (例: standard.lucene, ja.lucene, ja.microsoft, en.microsoft) を指定すれば、その完成形の分析パイプラインが走ります。', descEn: 'Set analyzer to a built-in name (e.g. standard.lucene, ja.lucene, ja.microsoft, en.microsoft) to run the full predefined pipeline.', targetSelector: '[data-guide-target="analyze-analyzer"]' },
        { icon: 'tools', titleJa: 'tokenizer + filters (パターン B)', titleEn: 'tokenizer + filters (option B)', descJa: 'analyzer の代わりに tokenizer (例: keyword, ngram, microsoft_language_tokenizer) と tokenFilters / charFilters の配列を指定すると、自作組み合わせの動作確認ができます。', descEn: 'Instead of analyzer, set tokenizer (e.g. keyword, ngram, microsoft_language_tokenizer) plus tokenFilters / charFilters arrays to test custom compositions.' },
        { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: 'Execute すると tokens 配列が返り、各トークンの token / startOffset / endOffset / position / type が確認できます。', descEn: 'Execute returns the tokens array with token / startOffset / endOffset / position / type for each token.', targetSelector: '[data-guide-target="execute-button"]' },
        { icon: 'eye', titleJa: '結果から学ぶ観点', titleEn: 'What to read in the result', descJa: '(1) 期待した分割粒度になっているか、(2) ストップワードが消えているか、(3) 小文字化や正規化 (NFKC, lowercase, asciifolding 等) が効いているか、(4) 同義語が展開されているか、を順に確認すると改善ポイントが見えます。', descEn: 'Inspect (1) tokenization granularity, (2) whether stopwords were removed, (3) lowercase/normalization (NFKC, lowercase, asciifolding…), (4) synonym expansion. This sequence pinpoints what to tune.' },
      ],
      tipsJa: [
        '日本語は ja.lucene (Lucene Kuromoji) と ja.microsoft (MS 形態素解析) で得意分野が違います。固有名詞や複合語は Microsoft 系が強い傾向、ニュース文は Lucene でも十分なケースが多いです。',
        '検索クエリ側とインデックス側で同じアナライザーを使わないとマッチしません。Analyze API で「クエリ語が同じトークンに正規化されるか」を必ず確認しましょう。',
        'ja.microsoft は形態素解析でストップワードに当たる助詞などを除去します。短いキーワード検索を意図しているならこれが効きます。',
        'カスタムアナライザーはインデックス定義の analyzers / tokenizers / tokenFilters / charFilters セクションで宣言してから analyze API で名前指定できます。',
        'シノニムマップを試したいときは、Synonym Map Builder で公開済みのマップ名をフィールドに紐付けたうえで synonyms フィルター相当の挙動を確認してください (Analyze 単体ではなく検索でも検証)。',
        '"会議の議事録について教えて" のような自然文を入れて、ストップワード相当の語が消えているか観察すると、無駄なトークン汚染を避けられます。',
      ],
      tipsEn: [
        'For Japanese, ja.lucene (Lucene Kuromoji) and ja.microsoft (MS morphological) have different strengths. MS handles named entities/compounds well; ja.lucene is often enough for news-style text.',
        'Query-side and index-side analyzers must match for terms to align. Always verify with Analyze API that query terms normalize to the same tokens as indexed text.',
        'ja.microsoft uses morphological analysis to drop particles and similar tokens — great for short keyword queries.',
        'Custom analyzers are declared in the index definition (analyzers / tokenizers / tokenFilters / charFilters), then referenced by name in the Analyze API.',
        'To validate synonym maps, attach the map to the field and observe behavior in actual search queries; the Analyze API alone does not show synonym expansion.',
        'Feed natural sentences (e.g. “会議の議事録について教えて”) and watch which tokens survive — this prevents stopword-style noise from contaminating the index.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-analyzers',
    },
  },

  // ── Builder Tools ────────────────────────────────────────────
  {
    id: 'index-builder',
    icon: 'bookmark-star',
    category: 'builder',
    titleJa: 'Index Builder',
    titleEn: 'Index Builder',
    descJa: 'インデックスのスキーマ作成・編集・削除。統計情報の表示、JSON インポート/エクスポート。',
    descEn: 'Create, edit, and delete index schemas. View statistics, import/export JSON.',
    action: 'openIndexBuilder',
    guide: {
      stepsJa: 'Index Builder の使い方',
      stepsEn: 'How to use Index Builder',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューまたはこのカードから Index Builder を開きます。接続中の Search サービスに対して Indexes のオペレーションを行います。', descEn: 'Open Index Builder from the Tools menu or this card. Operations target the currently connected search service.' },
        { icon: 'list-ul', titleJa: '一覧と詳細閲覧', titleEn: 'List & details', descJa: '左側に GET /indexes で取得したインデックス名一覧、選択すると documentCount / storageSize / vectorIndexSize の統計も確認できます (GET /indexes/{name}/stats)。', descEn: 'The left pane lists indexes from GET /indexes; selecting one shows documentCount / storageSize / vectorIndexSize from GET /indexes/{name}/stats.', targetSelector: '[data-guide-target="index-builder-list"]' },
        { icon: 'code-slash', titleJa: 'JSON エディタで定義', titleEn: 'Author in the JSON editor', descJa: 'fields には name / type (Edm.String, Collection(Edm.Single) など) / key / searchable / filterable / sortable / facetable / retrievable / analyzer を定義します。ベクトルフィールドは dimensions と vectorSearchProfile を必ず指定します。', descEn: 'In fields, set name / type (Edm.String, Collection(Edm.Single)…) / key / searchable / filterable / sortable / facetable / retrievable / analyzer. Vector fields require dimensions and vectorSearchProfile.', targetSelector: '[data-guide-target="index-builder-editor"]' },
        { icon: 'diagram-3', titleJa: 'vectorSearch を定義', titleEn: 'Define vectorSearch', descJa: 'vectorSearch.algorithms (HNSW パラメータ m / efConstruction / efSearch / metric)、profiles (algorithm + vectorizer + compression を束ねる)、vectorizers (例: azureOpenAI の endpoint/deploymentId)、compressions (scalarQuantization / binaryQuantization) を定義します。', descEn: 'Configure vectorSearch.algorithms (HNSW: m / efConstruction / efSearch / metric), profiles (algorithm + vectorizer + compression), vectorizers (e.g. azureOpenAI endpoint/deploymentId), and compressions (scalarQuantization / binaryQuantization).' },
        { icon: 'stars', titleJa: 'semantic と scoringProfiles', titleEn: 'semantic & scoringProfiles', descJa: 'semantic.configurations に titleField / contentFields / keywordsFields をマッピングするとセマンティック検索が使えるようになります。scoringProfiles では freshness/distance/tag/magnitude 関数と重みを定義します。', descEn: 'Mapping titleField / contentFields / keywordsFields under semantic.configurations enables semantic search. scoringProfiles let you define freshness/distance/tag/magnitude functions and weights.' },
        { icon: 'cloud-upload', titleJa: 'Create / Update', titleEn: 'Create / Update', descJa: 'Create は新規作成 (POST /indexes)、Update は既存インデックスを PUT で更新します。フィールドの型変更や key フィールドの変更はサポートされず、エラーになるため事前に Diff を確認しましょう。', descEn: 'Create posts a new index (POST /indexes); Update PUTs an existing one. Field type changes or key changes are not supported and will fail — review the diff first.', targetSelector: '[data-guide-target="index-builder-actions"]' },
        { icon: 'trash3', titleJa: '削除 (注意)', titleEn: 'Delete (caution)', descJa: 'DELETE /indexes/{name} は復元不可です。本番は Alias を介してスワップ、古いインデックスの削除はダウンタイムを見てからにします。', descEn: 'DELETE /indexes/{name} is irreversible. In production, swap behind an Alias and only delete the old index after a safe window.' },
      ],
      tipsJa: [
        'JSON インポートで既存テンプレートを読み込んで修正するのが最速。エクスポートした JSON はそのまま CI/CD パイプラインで使えます。',
        '検索品質は、key フィールドは Edm.String + retrievable=true / filterable=true / sortable=false (コスト削減)、本文フィールドは searchable=true にそろえるのが基本。',
        'ベクトルフィールドの dimensions は使う埋め込みモデルに合わせる (text-embedding-3-small=1536, ada-002=1536, large=3072)。途中で変えるとインデックスごと作り直しになります。',
        'ストレージ削減には compressions (scalarQuantization int8 で約 4 分の 1) と stored=false (結果返却不要なベクトルは保存しない) が効果的。Vector Optimizer で事前見積もり可。',
        'suggesters を定義しておくと Suggest / Autocomplete API が使えるようになります。予測入力 UI を作るときに必須。',
        'Index は Replicas (可用性・QPS) と Partitions (ストレージ・QPS) の 2 軸でスケールします。スキーマそのものとは独立なため、本番 SKU 選定時に考慮します。',
      ],
      tipsEn: [
        'Fastest authoring loop: import an existing template, edit, then export. Exported JSON drops straight into CI/CD pipelines.',
        'Quality baseline: key as Edm.String + retrievable=true / filterable=true / sortable=false (cost saver); body fields as searchable=true.',
        'Match vector dimensions to the embedding model you use (text-embedding-3-small=1536, ada-002=1536, large=3072). Changing dimensions later requires a full rebuild.',
        'For storage savings, combine compressions (scalarQuantization int8 ≈ 4× reduction) with stored=false on vectors you don’t return. Vector Optimizer can preview the impact.',
        'Define suggesters to enable Suggest / Autocomplete APIs — mandatory for type-ahead UIs.',
        'Indexes scale on two axes: Replicas (availability + QPS) and Partitions (storage + QPS). Plan SKU sizing accordingly.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-how-to-create-search-index',
    },
  },
  {
    id: 'synonym-map-builder',
    icon: 'journal-text',
    category: 'builder',
    titleJa: 'Synonym Map Builder',
    titleEn: 'Synonym Map Builder',
    descJa: 'Solr 形式のシノニムマップを作成・編集。同義語と明示的マッピングに対応。',
    descEn: 'Create and edit Solr-format synonym maps. Supports equivalency and explicit mappings.',
    action: 'openSynonymMapBuilder',
    guide: {
      stepsJa: 'Synonym Map Builder の使い方',
      stepsEn: 'How to use Synonym Map Builder',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Synonym Map Builder を開きます。接続中 Search サービスの GET /synonymmaps を読み取ります。', descEn: 'Open Synonym Map Builder from the Tools menu. Loads via GET /synonymmaps from the connected service.' },
        { icon: 'list-ul', titleJa: 'マップ選択 / 新規', titleEn: 'Select / new map', descJa: '左ペインで既存マップを選択するか、新規作成します。名前はサービス内で一意、小文字/数字/ハイフンのみ使用可能です。', descEn: 'Pick an existing map in the left pane, or create a new one. Names must be unique within the service and may only contain lowercase letters, digits, and dashes.', targetSelector: '[data-guide-target="synonym-map-list"]' },
        { icon: 'pencil-square', titleJa: 'ルールを記述', titleEn: 'Author rules', descJa: '1 行 1 ルール。等価: "laptop, notebook, portable computer" / 明示: "USA, U.S.A. => United States"。明示マッピングでは右辺だけがインデックスに保存されるトークンになり、左辺はクエリ時のマッチだけに使われます。', descEn: 'One rule per line. Equivalence: "laptop, notebook, portable computer". Explicit: "USA, U.S.A. => United States". With explicit mapping, only the right-hand side is stored at index time; left-hand side is used purely as query-time match.', targetSelector: '[data-guide-target="synonym-map-editor"]' },
        { icon: 'cloud-upload', titleJa: '公開', titleEn: 'Publish', descJa: 'Save で PUT /synonymmaps/{name} を送信します。重要: シノニムマップを作成しただけでは検索動作は変わりません。インデックスの Searchable フィールドに synonymMaps としてアタッチして初めて適用されます。', descEn: 'Save sends PUT /synonymmaps/{name}. Important: creating the map alone does NOT change search behavior. You must attach it as synonymMaps on a Searchable field in the index definition.', targetSelector: '[data-guide-target="synonym-map-actions"]' },
        { icon: 'plug', titleJa: 'インデックスへアタッチ', titleEn: 'Attach to the index', descJa: 'Index Builder で対象フィールドに "synonymMaps": ["my-map"] を追加し、インデックスを Update。効いているかは実検索で応答を見て確認します。', descEn: 'In Index Builder, add "synonymMaps": ["my-map"] to the target field and Update the index. Verify by running a search and inspecting results.' },
      ],
      tipsJa: [
        'シノニム展開はクエリ時だけでなく、インデックス作成時にも適用されます (作成済みドキュメントには遡及しない)。マップを変えた場合はインデックス再ビルドが必要なことがあります。',
        '明示マッピング (=>) は「見出し語を正規名に集約」したいとき、等価は「どちらで検索されても他もヒットさせたい」ときに使います。両者の使い分けが品質の要。',
        '1 シノニムマップあたり最大 5,000 ルール、サービスあたりマップサイズ上限 (SKU ごと) に注意。',
        '同一フィールドに複数マップをアタッチできます。ドメイン別 (商品名シノニム、略語シノニム) に分けて管理しやすくします。',
        'シノニムとアナライザーの順序に注意。小文字化・ステミング計算後にシノニム拡張が走るため、シノニム側も同じ表記揃えが必要なケースがあります。',
        'CI/CD では generateSynonymMap.mjs スクリプトや JSON インポートを使うと、スプレッドシートから一括生成できます。',
      ],
      tipsEn: [
        'Synonym expansion runs at both query time AND index time (but does NOT retroactively rewrite already-indexed docs). Changing a map may require a rebuild.',
        'Use explicit mapping (=>) to canonicalize variants into one form; use equivalence to make all forms findable from any. Picking the right mode is the key quality lever.',
        'Limits: up to 5,000 rules per map and a per-service map size limit (varies by SKU).',
        'You can attach multiple maps to one field. Split by domain (product names / acronyms…) for cleaner ownership.',
        'Order matters with analyzers: synonyms expand AFTER lowercasing/stemming, so spell synonym entries to match the analyzed form.',
        'For CI/CD use the generateSynonymMap.mjs script or JSON import to mass-produce maps from spreadsheets.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-synonyms',
    },
  },
  {
    id: 'knowledge-source-builder',
    icon: 'collection',
    category: 'builder',
    titleJa: 'Knowledge Source Builder',
    titleEn: 'Knowledge Source Builder',
    descJa: 'Agentic Retrieval 用のナレッジソースを作成・管理。',
    descEn: 'Create and manage knowledge sources for Agentic Retrieval.',
    action: 'openKnowledgeSourceBuilder',
    guide: {
      stepsJa: 'Knowledge Source Builder の使い方',
      stepsEn: 'How to use Knowledge Source Builder',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Knowledge Source Builder を開きます。preview API (2025-08-01-preview 系) で動作します。', descEn: 'Open Knowledge Source Builder from the Tools menu. Operates against a preview API (2025-08-01-preview family).' },
        { icon: 'plus-circle', titleJa: '基本情報を入力', titleEn: 'Enter the basics', descJa: 'name (Knowledge Base から参照される ID)、kind (例: searchIndex)、参照する searchIndexName と semanticConfiguration 名を指定します。事前にインデックスとセマンティック構成が必要。', descEn: 'Set name (the ID referenced from a Knowledge Base), kind (e.g. searchIndex), the target searchIndexName, and a semanticConfiguration name. The index and semantic config must exist beforehand.', targetSelector: '[data-guide-target="knowledge-source-form"]' },
        { icon: 'chat-text', titleJa: 'description を丁寧に書く', titleEn: 'Write a precise description', descJa: 'この説明文は Agent が「どのソースを使うか」を判断する主要資料です。「社内 FAQ、人事・勤怠関連」「2024 年度以降の製品マニュアル」のようにユースケースを具体的に記述すると選択精度が上がります。', descEn: 'The description is the primary signal an Agent uses to decide whether to query this source. Be specific (“Internal HR/attendance FAQ”, “Product manuals from FY2024 onward”) for higher selection accuracy.' },
        { icon: 'gear', titleJa: 'フィールドマッピング', titleEn: 'Field mappings', descJa: 'sourceDataFields にはそのソースが提供するフィールド (id, title, content, url, …)、searchFields にはクエリ側で使われるフィールドをマッピングします。これにより Knowledge Base / Agent が一貫したスキーマとしてソースを扱えます。', descEn: 'sourceDataFields lists fields the source exposes (id, title, content, url…); searchFields maps to fields used at query time. This lets the Knowledge Base / Agent treat the source through a uniform schema.', targetSelector: '[data-guide-target="knowledge-source-fields"]' },
        { icon: 'cloud-upload', titleJa: '公開', titleEn: 'Publish', descJa: 'Save で PUT /knowledgeSources/{name} (preview) を送信します。公開後は Knowledge Base Builder の knowledgeSources 配列から参照できます。', descEn: 'Save sends PUT /knowledgeSources/{name} (preview). Once published, it can be referenced from the knowledgeSources array in Knowledge Base Builder.', targetSelector: '[data-guide-target="knowledge-source-actions"]' },
      ],
      tipsJa: [
        'Knowledge Source は不可分な「検索単位」です。目的やドメインごとに分け、最終的に Knowledge Base で合成するのが推奨パターン。',
        'description はユーザーではなく「LLM が読む」前提で書きましょう。扱うトピック / 期間 / 対象の 3 要素が入っていると選択精度が上がります。',
        'セマンティック構成がよく設定されているインデックスほど Agent の回答品質が上がります。titleField/contentFields のマッピングを見直す価値あり。',
        '1 つのインデックスに対して複数の Knowledge Source (例: 「募集要項」「社内ポリシー」と同じインデックスだが description とフィルタを変えたもの) を定義し、Agent に使い分けさせるパターンも有効です。',
        'Agentic Retrieval は preview 機能のため、API バージョンやスキーマが今後変わる可能性があります。本番適用前に最新公式ドキュメントで可用性を確認してください。',
      ],
      tipsEn: [
        'Knowledge Source is the atomic retrievable unit. Split by purpose/domain and compose with Knowledge Base — the recommended pattern.',
        'Write description for the LLM, not for human users. Mentioning topic / time period / audience tends to maximize selection accuracy.',
        'Indexes with strong semantic configurations yield better Agent answers — worth tuning titleField/contentFields mappings.',
        'You can define multiple Knowledge Sources over the same index (e.g. one for “hiring policies”, another for “internal policies”) with different descriptions/filters to bias the Agent’s choice.',
        'Agentic Retrieval is preview — API version and schema may change. Verify against current official docs before going live.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-agentic-retrieval-how-to-create',
    },
  },
  {
    id: 'knowledge-base-builder',
    icon: 'database',
    category: 'builder',
    titleJa: 'Knowledge Base Builder',
    titleEn: 'Knowledge Base Builder',
    descJa: 'ナレッジベースの作成・編集。複数のナレッジソースを束ねて管理。',
    descEn: 'Create and edit knowledge bases. Bundle multiple knowledge sources.',
    action: 'openKnowledgeBaseBuilder',
    guide: {
      stepsJa: 'Knowledge Base Builder の使い方',
      stepsEn: 'How to use Knowledge Base Builder',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Knowledge Base Builder を開きます。preview API で動作します。', descEn: 'Open Knowledge Base Builder from the Tools menu. Uses the preview API.' },
        { icon: 'plus-circle', titleJa: '基本情報を入力', titleEn: 'Enter basics', descJa: 'name (Agentic Retrieval クエリで指定される ID)、description (会話エージェントの用途説明) を入力します。', descEn: 'Set name (the ID specified by Agentic Retrieval queries) and description (high-level purpose of the agent).', targetSelector: '[data-guide-target="knowledge-base-form"]' },
        { icon: 'cpu', titleJa: 'Knowledge Agent (LLM) を接続', titleEn: 'Bind a Knowledge Agent (LLM)', descJa: 'Azure OpenAI の endpoint / deployment ID / API キー またはマネージド ID 認証を設定します。サブクエリ計画と最終応答生成をこのデプロイメントが担当します。', descEn: 'Configure the Azure OpenAI endpoint / deployment ID / API key (or managed identity). This deployment plans subqueries and synthesizes the final response.' },
        { icon: 'collection', titleJa: 'knowledgeSources を追加', titleEn: 'Add knowledgeSources', descJa: '事前に公開した Knowledge Source を配列に追加。複数追加すると Agent がクエリごとに「どれを使うか」を自動選択します。選択ロジックは各 Source の description に依存します。', descEn: 'Add previously published Knowledge Sources to the array. With multiple sources, the Agent picks per query — selection logic depends on each source’s description.', targetSelector: '[data-guide-target="knowledge-base-sources"]' },
        { icon: 'cloud-upload', titleJa: '公開', titleEn: 'Publish', descJa: 'Save で PUT /knowledgeBases/{name} (preview) を送信。公開後は Lab Mode = Agentic でドロップダウンに表示され、Agentic Retrieval で使えるようになります。', descEn: 'Save sends PUT /knowledgeBases/{name} (preview). After publishing, it appears in the dropdown when Lab Mode = Agentic and is usable in Agentic Retrieval.', targetSelector: '[data-guide-target="knowledge-base-actions"]' },
      ],
      tipsJa: [
        '1 つの Knowledge Base に 1 つのドメイン (製品 / 社内規程 / サポートなど) を対応させ、Source でサブトピックを分割すると選択精度と説明性が上がります。',
        'トークン消費は「入力会話 + サブクエリ + 検索結果 + 最終応答」の合計です。コストを押さえるなら Source 側の返却サイズ・チャンク長 と retrievalReasoningEffort を調整しましょう。',
        'Agent デプロイメントはツール呼び出し・ JSON 出力に対応したモデル (gpt-4o, gpt-4o-mini, o3-mini等) を推奨。ガードレールやクオータ不足はエラーの原因になりやすいです。',
        '未公開の Source を knowledgeSources に入れると公開時にエラー。必ず先に Knowledge Source を公開しておきましょう。',
        'Knowledge Base と Source は両方とも preview スキーマです。バージョンアップ時は Index Builder や Synonym Map と同様、Diff を見てから適用しましょう。',
      ],
      tipsEn: [
        'Map one Knowledge Base per domain (product / internal policy / support…) and split subtopics into Sources — improves selection accuracy and explainability.',
        'Token cost = input messages + subqueries + retrieved chunks + final synthesis. To control cost, tune Source-side return size / chunk length and retrievalReasoningEffort.',
        'Pick an Agent deployment that supports tool calling and JSON output (gpt-4o, gpt-4o-mini, o3-mini, etc.). Guardrails or quota shortages cause runtime errors.',
        'Putting an unpublished Source into knowledgeSources will fail at publish time — always publish Sources first.',
        'Both Knowledge Base and Source are preview schemas. Treat upgrades like index/synonym deploys: review the diff before applying.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-agentic-retrieval-how-to-create',
    },
  },
  {
    id: 'skill-pipeline-builder',
    icon: 'diagram-2',
    isEmoji: false,
    category: 'builder',
    titleJa: 'Skill Pipeline Builder',
    titleEn: 'Skill Pipeline Builder',
    descJa: 'スキルセットをビジュアル DAG エディタで構築。15 種の組み込みスキルテンプレート、デバッグランナー付き。',
    descEn: 'Author skillsets with a visual DAG editor. 15 built-in skill templates with debug runner.',
    action: 'openSkillPipelineBuilder',
    guide: {
      stepsJa: 'Skill Pipeline Builder の使い方',
      stepsEn: 'How to use Skill Pipeline Builder',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Skill Pipeline Builder を開きます。キャンバス上で右クリックすると Indexer / Index / Skillset をサービスから読み込めます。', descEn: 'Open Skill Pipeline Builder from the Tools menu. Right-click the canvas to load Indexer / Index / Skillset from the connected service.' },
        { icon: 'plus-circle', titleJa: 'スキルノードを追加', titleEn: 'Add skill nodes', descJa: 'ツールバーから組み込みスキルテンプレートを選択して追加。例: SplitSkill (チャンク化), AzureOpenAIEmbeddingSkill (ベクトル化), OCR / Vision (画像), Custom Web API (コンテナースキル)。', descEn: 'Pick a built-in skill template from the toolbar to drop a node on the canvas. Examples: SplitSkill (chunking), AzureOpenAIEmbeddingSkill (vectorization), OCR / Vision (images), Custom Web API (container skills).', targetSelector: '[data-guide-target="spb-toolbar"]' },
        { icon: 'link-45deg', titleJa: 'ポートを接続', titleEn: 'Wire ports', descJa: '出力ポートをドラッグして次のスキルの入力ポートに接続。エンリッチメントパス (例: /document/pages/*/content) が自動計算されるため、JSON 手書きよりミスが起きにくいです。', descEn: 'Drag from an output port to the next skill’s input port. Enrichment paths (e.g. /document/pages/*/content) are computed automatically — less error-prone than hand-writing JSON.', targetSelector: '[data-guide-target="spb-canvas"]' },
        { icon: 'sliders', titleJa: 'ノードパラメータを編集', titleEn: 'Edit node parameters', descJa: 'ノードをクリックすると右ペインで context (スキル適用単位) / inputs / outputs / 設定パラメータ (e.g. SplitSkill.maximumPageLength, EmbeddingSkill.deploymentId) を編集できます。', descEn: 'Click a node to edit its context (the unit at which the skill is applied), inputs, outputs, and parameters (e.g. SplitSkill.maximumPageLength, EmbeddingSkill.deploymentId) in the right pane.' },
        { icon: 'code-slash', titleJa: 'Skillset JSON タブ', titleEn: 'Skillset JSON tab', descJa: 'Skillset JSON タブで PUT /skillsets/{name} に送る body を直接編集可能。グラフと JSON は双方向同期され、どちらでも作業できます。', descEn: 'The Skillset JSON tab lets you edit the body sent to PUT /skillsets/{name} directly. Graph and JSON are kept in sync, so you can switch back and forth.', targetSelector: '[data-guide-target="spb-tab-skillsetJson"]' },
        { icon: 'bug', titleJa: 'Debug Runner', titleEn: 'Debug Runner', descJa: 'Debug Runner タブで 1 件のサンプル document を JSON で与え、各スキルの出力をステップごとにプレビュー。Indexer を回さずに enrichment tree を検証できます。', descEn: 'In Debug Runner, supply one sample document as JSON and preview each skill’s output step by step. Verifies the enrichment tree without running the Indexer.', targetSelector: '[data-guide-target="spb-tab-debugRunner"]' },
        { icon: 'cloud-upload', titleJa: 'Diff 付きで公開', titleEn: 'Publish with diff', descJa: 'Publish で Skillset (PUT /skillsets/{name})、必要に応じて Index / Indexer も同時に Diff 確認付きで公開できます。ツールが差分を表示してくれるので事故防止に有効。', descEn: 'Publish pushes the Skillset (PUT /skillsets/{name}) and optionally the Index / Indexer in one go, with a diff confirmation — a useful safety net.', targetSelector: '[data-guide-target="spb-publish"]' },
      ],
      tipsJa: [
        'context は「このスキルを何の単位で走らせるか」を決める重要な設定です。例: /document は 1 ドキュメントに 1 回、/document/pages/* はページごとに実行。計算量に直結。',
        'AzureOpenAIEmbeddingSkill を使う場合はインデックスのベクトルフィールド dimensions と deploymentId のモデル出力次元を一致させてください。不一致はインデクサーエラーの主要原因です。',
        'WebApiSkill (カスタムスキル) は Azure Container Apps 上に乗せて、このスタジオの Custom Skill LiveEditor からデプロイできます。',
        '公開前に Debug Runner で 1 ドキュメントを実行しておくと、Indexer で初めてエラーに気付いてインデクシングが全滅する事故を防げます。',
        'Skillset の変更は既存ドキュメントに遡及適用されません (Indexer を reset → 再実行が必要)。本番では Indexer history を見て計画を。',
        '複雑な DAG はローカル保存で .json として保管し、レビューや PR に載せられるようにしておくと便利です。',
      ],
      tipsEn: [
        'context controls the unit at which a skill runs: /document = once per doc, /document/pages/* = once per page. It directly affects compute volume and cost.',
        'When using AzureOpenAIEmbeddingSkill, ensure the index vector field’s dimensions match the deployment’s output dimensionality — mismatch is a top cause of indexing failures.',
        'WebApiSkill (custom skills) can target Azure Container Apps and be deployed via this studio’s Custom Skill LiveEditor.',
        'Run Debug Runner on one document before publishing — prevents wholesale Indexer failures from a small mistake.',
        'Skillset edits are NOT retroactive on already-indexed docs (you must reset the Indexer and re-run). Plan production changes via Indexer history.',
        'For complex DAGs, use local save to keep .json snapshots and route them through PR review.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/cognitive-search-defining-skillset',
    },
  },
  {
    id: 'skill-code-editor',
    icon: 'code-slash',
    category: 'builder',
    titleJa: 'Custom Skill LiveEditor',
    titleEn: 'Custom Skill LiveEditor',
    descJa: 'Python カスタムスキルをブラウザ内で開発・テスト・デプロイ。Pyodide によるローカル実行対応。',
    descEn: 'Develop, test, and deploy Python custom skills in-browser. Local execution via Pyodide.',
    action: 'openSkillEditor',
    guide: {
      stepsJa: 'Custom Skill LiveEditor の使い方',
      stepsEn: 'How to use Custom Skill LiveEditor',
      steps: [
        { icon: 'code-slash', titleJa: 'Code タブ: スキルを記述', titleEn: 'Code tab: write the skill', descJa: 'Code タブに Python でスキルを記述。エントリポイントは def process(input: dict) -> dict。入力は WebApiSkill が送る values 配列の 1 レコード (data フィールド)、出力は errors / warnings / data を含む dict を返します。', descEn: 'Write Python in the Code tab. Entry point is def process(input: dict) -> dict. Input is one record from the WebApiSkill values array (data field). Return a dict with errors / warnings / data.', targetSelector: '[data-guide-target="sce-tab-code"]' },
        { icon: 'terminal', titleJa: 'Test タブ: Local Run で検証', titleEn: 'Test tab: Local Run', descJa: 'Test タブでサンプル入力 JSON を与え、Local Run (Pyodide) を押すとブラウザ内 (WebAssembly) で即時に実行されます。サーバー不要でデバッグ可能。', descEn: 'In the Test tab, supply a sample input JSON and click Local Run (Pyodide). Code executes inside the browser (WebAssembly) for instant, server-less debugging.', targetSelector: '[data-guide-target="sce-tab-test"]' },
        { icon: 'cloud', titleJa: 'Test タブ: Remote Run', titleEn: 'Test tab: Remote Run', descJa: 'Remote Run は Settings で設定した Skill Runtime URL (例: ACA にデプロイした FastAPI) に POST して本番同等の実行パスを検証します。Network タブでリクエスト/レスポンスを見れるため WebApiSkill デバッグに最適。', descEn: 'Remote Run POSTs to the Skill Runtime URL configured in Settings (e.g. a FastAPI on ACA), validating the production execution path. The Network tab shows request/response — ideal for WebApiSkill debugging.' },
        { icon: 'gear', titleJa: 'Settings タブ: ランタイム接続', titleEn: 'Settings tab: runtime connection', descJa: 'Skill Runtime URL、認証設定 (API key / Bearer)、Health Check を設定。Health を押すと /health への ping で ACA コンテナーの生存を確認できます。', descEn: 'Configure Skill Runtime URL, auth (API key / Bearer), and Health Check. Hit Health to ping /health and verify the ACA container is alive.', targetSelector: '[data-guide-target="sce-tab-settings"]' },
        { icon: 'cloud-upload', titleJa: 'Settings タブ: デプロイ', titleEn: 'Settings tab: deploy', descJa: 'Settings からコードを Azure Blob Storage にアップロードし、ACA 側のコンテナーに反映。スキルランタイムは scripts/skill-runtime/ 下のスクリプトで ACA を生成/更新してから使います。', descEn: 'Upload code from Settings to Azure Blob Storage and apply it to the ACA container. The skill runtime itself is provisioned/updated via the scripts under scripts/skill-runtime/.', targetSelector: '[data-guide-target="sce-tab-settings"]' },
        { icon: 'plug', titleJa: 'Skillset と接続', titleEn: 'Wire into a skillset', descJa: 'Skill Pipeline Builder で WebApiSkill ノードを追加し、uri に ACA エンドポイント、httpHeaders/timeout などを設定。ノード上の「Open in LiveEditor」からこのエディタを直接起動できます。', descEn: 'In Skill Pipeline Builder, add a WebApiSkill node and configure uri to your ACA endpoint plus httpHeaders / timeout. “Open in LiveEditor” on a node launches this editor directly.' },
      ],
      tipsJa: [
        'Local Run (Pyodide) は手軽ですがピュア Python (一部の C 拡張を除く) しか動きません。本番同等の検証は Remote Run で必ず行いましょう。',
        'WebApiSkill の入出力スキーマは厳密です (recordId と errors/warnings/data のセット)。スキーマを崩すと Indexer がドキュメントごとに失敗します。',
        '例外は raise せずに errors 配列に詰めて返すと Indexer が他のドキュメントを続行できます。warnings はログとして使いましょう。',
        'Indexer はバッチで複数レコードを送ってきます。process 関数を values 配列のループ処理に対応させるか、サーバー側でラッパーを用意してください。',
        'ACA と Search サービス間は Search のマネージド ID と ACA のイングレス設定 (Public / VNet) を揃えると認証がシンプルになります。セキュリティ面でも推奨。',
        'サンプル実装から始める場合は、skill-runtime 側のサンプルや README にある WebApiSkill の例を参照してください。',
      ],
      tipsEn: [
        'Local Run (Pyodide) is convenient but only supports pure Python (most C extensions are off-limits). Always validate the production path with Remote Run.',
        'WebApiSkill’s I/O schema is strict (recordId + errors/warnings/data). Breaking it makes the Indexer fail per-document.',
        'Return errors in the array instead of raising — the Indexer can keep processing other docs. Use warnings for log-style messages.',
        'Indexers send batches. Either let process iterate the values array, or implement a wrapper on the server side.',
        'Between ACA and Search, use Search’s managed identity and align ACA ingress (Public / VNet) for clean auth — also recommended for security.',
        'If you want to start from a sample, refer to the WebApiSkill examples in the skill-runtime samples or README.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/cognitive-search-custom-skill-web-api',
    },
  },
  {
    id: 'filter-builder',
    icon: 'funnel',
    category: 'builder',
    titleJa: 'Filter Builder',
    titleEn: 'Filter Builder',
    descJa: 'OData フィルター式を GUI で構築。複数条件の AND/OR ロジックに対応。',
    descEn: 'Build OData filter expressions via GUI. Supports AND/OR logic with multiple conditions.',
    action: 'openFilterBuilder',
    guide: {
      stepsJa: 'Filter Builder の使い方',
      stepsEn: 'How to use Filter Builder',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'Request Builder の filter フィールド横のボタンから起動。インデックススキーマを読み込み、Filterable=true のフィールドのみを候補表示します。', descEn: 'Open from the button next to the Request Builder filter field. The tool reads the index schema and only offers Filterable=true fields.' },
        { icon: 'plus-circle', titleJa: '条件を追加', titleEn: 'Add a condition', descJa: 'フィールド名 / 演算子 / 値を選択して標準的な OData 式を生成。例: category eq \'docs\', price ge 100, createdAt gt 2024-01-01T00:00:00Z (ISO 8601 UTC)。', descEn: 'Pick field / operator / value to assemble the canonical OData expression. Examples: category eq \'docs\', price ge 100, createdAt gt 2024-01-01T00:00:00Z (ISO 8601 UTC).' },
        { icon: 'list-check', titleJa: '複数値は search.in', titleEn: 'Use search.in for multi-value', descJa: '"このタグのいずれか」は search.in(field, \'docs,faqs,policies\') と書くのが高速で読みやすいです。OR を並べるよりスケールします。', descEn: 'For “any of these tags”, prefer search.in(field, \'docs,faqs,policies\') over chained ORs — faster and cleaner.' },
        { icon: 'collection', titleJa: 'Collection には any/all', titleEn: 'Use any/all on collections', descJa: 'Collection(Edm.String) などのコレクションフィールドは tags/any(t: t eq \'urgent\') や ratings/all(r: r ge 3) のようにラムダを使います。', descEn: 'On collection fields (Collection(Edm.String) etc.), use lambdas: tags/any(t: t eq \'urgent\') or ratings/all(r: r ge 3).' },
        { icon: 'diagram-3', titleJa: 'AND / OR とグループ', titleEn: 'AND / OR & grouping', descJa: '複数条件を AND/OR で結合し、()でグループ。例: (category eq \'docs\' or category eq \'faq\') and price lt 100。手書きで誤りやすい部分を GUI がそのまま表現します。', descEn: 'Combine conditions with AND/OR and group with parentheses, e.g. (category eq \'docs\' or category eq \'faq\') and price lt 100. The GUI mirrors what is otherwise easy to mistype.' },
        { icon: 'check2-circle', titleJa: 'プレビュー & 適用', titleEn: 'Preview & apply', descJa: '生成されたクエリ文字列をプレビューし、Apply で Request Builder の filter へ反映。そのまま Execute で検索に反映されます。', descEn: 'Preview the generated string and Apply to push it into Request Builder’s filter. Execute uses it immediately.' },
      ],
      tipsJa: [
        '文字列リテラルはシングルクオート (\'docs\')。文字列内にシングルクオートを含めたいときは \'\' のように 2 つ重ねるのが OData のルールです。検索クエリ文字列とは別ルールなので要注意。',
        '日付型は Edm.DateTimeOffset 、値は ISO 8601 UTC (例: 2024-04-01T00:00:00Z)。タイムゾーン付きで与えるとエラー、または意図しないシフトになります。',
        '距離検索は geo.distance(loc, geography\'POINT(lon lat)\') lt 5 のように記述。Edm.GeographyPoint フィールドが必要です。',
        'BM25 スコアを保ちつつフィルタしたいときは search.ismatchscoring(\'キーワード\', \'title\') を使うと OR としても作用します。',
        'NULL チェックは field eq null / field ne null で明示。論理型は true/false を Boolean リテラルとしてそのまま書きます (引用不要)。',
        'ベクトル・ハイブリッド検索と併用するときは vectorFilterMode (preFilter / postFilter) の振る舞いに注意。preFilter は候補を先に絞り、精度と latency のバランスが良いです。',
      ],
      tipsEn: [
        'String literals use single quotes (\'docs\'); to embed a single quote, double it (OData rule). This is different from search’s text query syntax.',
        'Date fields are Edm.DateTimeOffset and values must be ISO 8601 UTC (e.g. 2024-04-01T00:00:00Z). Local time zones cause errors or wrong shifts.',
        'Geo distance: geo.distance(loc, geography\'POINT(lon lat)\') lt 5. Requires an Edm.GeographyPoint field.',
        'To filter while keeping BM25 scoring, use search.ismatchscoring(\'keyword\', \'title\') — it acts as a soft OR.',
        'NULL checks: field eq null / field ne null. Booleans are written as true/false without quotes.',
        'Hybrid/vector + filter: watch vectorFilterMode (preFilter / postFilter). preFilter narrows candidates first — best balance of accuracy and latency.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-filters',
    },
  },

  // ── Optimization & Testing ───────────────────────────────────
  {
    id: 'auto-tuning',
    icon: 'sliders',
    category: 'optimization',
    titleJa: 'Search Parameter AutoTuning',
    titleEn: 'Search Parameter AutoTuning',
    descJa: 'JSONL 評価データセットを使ったグリッドサーチによる検索パラメータの自動最適化。',
    descEn: 'Automated grid search optimization of search parameters using JSONL evaluation datasets.',
    action: 'openAutoTuning',
    guide: {
      stepsJa: 'AutoTuning の使い方',
      stepsEn: 'How to use AutoTuning',
      steps: [
        { icon: 'file-earmark-arrow-up', titleJa: 'データセットアップロード', titleEn: 'Upload dataset', descJa: 'JSONL (1 行 1 サンプル)。必須は query (検索クエリ) と expected_ids (正解ドキュメント ID の配列)。任意で relevance スコア (NDCG 用) も入れられます。samples/autotuning-dataset-{ja,en}.jsonl が参考例。', descEn: 'Upload JSONL (one sample per line). Required keys: query (the query string) and expected_ids (array of ground-truth doc IDs). Optional relevance grades enable NDCG. See samples/autotuning-dataset-{ja,en}.jsonl.', targetSelector: '[data-guide-target="autotuning-upload"]' },
        { icon: 'list-ul', titleJa: 'インデックスと接続を確認', titleEn: 'Verify index & connection', descJa: 'expected_ids は実際にインデックスに存在する key と一致している必要があります。接続セクションと Index Inspector で key field と ID の推移を確認しましょう。', descEn: 'expected_ids must match real key values in the index. Use the Connection section and Index Inspector to verify the key field and value scheme.' },
        { icon: 'sliders', titleJa: 'パラメータ探索空間', titleEn: 'Define the parameter space', descJa: '最適化したいパラメータと候補値を選びます。例: queryType (text/vector/hybrid/semantic_hybrid)、vectorWeight (0.5/1/2)、vectorK (10/30/50)、top (10/30)。組み合わせ数 = 各軸の選択肢の積になるため、絞り込みが重要。', descEn: 'Pick which parameters and candidate values to sweep. Example: queryType (text/vector/hybrid/semantic_hybrid), vectorWeight (0.5/1/2), vectorK (10/30/50), top (10/30). Total runs = product of axes — keep it small.', targetSelector: '[data-guide-target="autotuning-params"]' },
        { icon: 'bullseye', titleJa: '評価指標と k', titleEn: 'Choose metric & k', descJa: '最適化目標に Precision@k (上位 k 件中の正解率)、Recall@k (正解中 k 件に入った割合)、NDCG@k (順位重み付きの関連度)、MRR (初出順位の逆数) から選択。k はユーザー提示件数に合わせるのが定石。', descEn: 'Pick the optimization target: Precision@k, Recall@k, NDCG@k (rank-weighted relevance), or MRR (1/rank of first hit). Set k to your real top-N for users.', targetSelector: '[data-guide-target="autotuning-metric"]' },
        { icon: 'play-circle', titleJa: '実行 & 進捗確認', titleEn: 'Run & track progress', descJa: 'Run で全組み合わせを並列実行。クエリごとに expected_ids と検索結果の key を照らしてメトリクスを計算し、全クエリ平均でランキングします。進捗バーと部分結果がリアルタイム表示されます。', descEn: 'Run dispatches all combinations in parallel. Each query’s metric is computed by comparing expected_ids with the result keys; combinations rank by mean across queries. Live progress and partial results are shown.', targetSelector: '[data-guide-target="autotuning-run"]' },
        { icon: 'clipboard-data', titleJa: '結果を読む', titleEn: 'Read the results', descJa: 'トップの組み合わせを採用して Request Builder へ反映、または Experiment Run として保存し後日比較。クエリ単位のスコアも見て、特定クエリだけ崩れていないかを確認しましょう。', descEn: 'Apply the top combination back to Request Builder, or save it as an Experiment Run for later comparison. Inspect per-query scores too — watch for individual queries dragging the mean down.' },
      ],
      tipsJa: [
        'データセットは「本番で見られるクエリ」と「オペレーターが付けた正解」のペアで、最低でも 30〜50 件は推奨。少なすぎると個別クエリのノイズで順位がぶれます。',
        'グリッド探索の計算量は探索点 × クエリ数に比例して増えます。探索点を ≤3軸 × ≤3値程度に押さえ、さらに広げたいときは複数ステップに分けるのが現実的。',
        'NDCG@k を使うには relevance スコア (0/1/2/3 など) がデータセットに必要。単純に「正解ドキュメントだけ」なら Recall@k / MRR が説明しやすいです。',
        'Top の組み合わせと 2番手のスコア差が有意かは要確認。サンプルサイズが小さいと「偽の勝者」になりがちです。',
        '結果は Experiment として保存されるため、後日同じデータセットでインデックス変更後の差を見るなど、レグレッションチェックに役立ちます。',
      ],
      tipsEn: [
        'A dataset is the pair of “real user-style queries” and “operator-curated answers”. Aim for at least 30–50 samples; smaller sets get noisy on individual queries.',
        'Grid search cost is points × queries. Keep the grid ≤ 3 axes × ≤ 3 values; if you want to extend further, run additional staged sweeps.',
        'NDCG@k requires graded relevance scores in the dataset (0/1/2/3 etc.). With only “correct doc IDs”, Recall@k / MRR are easier to interpret.',
        'Check whether the gap between rank 1 and rank 2 is meaningful — small samples often produce “fake winners”.',
        'Results persist as Experiments, so you can run the same dataset later (e.g. after an index change) and detect regressions.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-query-overview',
    },
  },
  {
    id: 'vector-optimizer',
    icon: 'arrows-angle-contract',
    category: 'optimization',
    titleJa: 'Vector Optimizer',
    titleEn: 'Vector Optimizer',
    descJa: '量子化・次元削減・ストレージ設定の組み合わせで理論サイズを比較。コスト最適化を支援。',
    descEn: 'Compare theoretical sizes for quantization, dimension reduction, and storage combinations.',
    action: 'openVectorOptimizer',
    guide: {
      stepsJa: 'Vector Optimizer の使い方',
      stepsEn: 'How to use Vector Optimizer',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Vector Optimizer を開きます。Azure AI Search のベクトルコンプレッション設定を GUI で見積もるツールです。', descEn: 'Open Vector Optimizer from the Tools menu. It’s a GUI for previewing Azure AI Search vector compression settings.' },
        { icon: 'sliders', titleJa: 'ベクトルの前提を入力', titleEn: 'Vector basics', descJa: '使う埋め込みモデルの dimensions (例: text-embedding-3-large=3072) とドキュメント数、読み込みフォーマット (float32 / float16 など) を設定します。', descEn: 'Set the embedding model’s dimensions (e.g. text-embedding-3-large = 3072), document count, and source format (float32 / float16).', targetSelector: '[data-guide-target="vo-dimensions"]' },
        { icon: 'gear', titleJa: '量子化と MRL', titleEn: 'Quantization & MRL', descJa: 'scalarQuantization (int8、約 1/4) / binaryQuantization (1bit、約 1/32 だが品質低下リスク) と truncationDimension (MRL: 約数の次元へ切り詰め) の組み合わせを選択します。rescoring=true なら全精度ベクトルで再検索し、上位のみ再スコアリングしてリコールを補えます。', descEn: 'Pick combinations of scalarQuantization (int8, ~4×) / binaryQuantization (1-bit, ~32× but quality risk) and truncationDimension (MRL truncation to a divisor). With rescoring=true, top results are re-scored against full-precision vectors to recover recall.', targetSelector: '[data-guide-target="vo-settings"]' },
        { icon: 'box-seam', titleJa: 'stored / retrievable', titleEn: 'stored / retrievable', descJa: 'クエリ結果としてベクトルを返却しないなら stored=false を推奨 (表示用ストレージが不要になり、サイズがその分削減)。retrievable とは別軸の設定で、検索計算中の HNSW ベクトルには影響しません。', descEn: 'If you do not return vectors as part of query results, set stored=false to drop the display copy and shrink storage. It is independent of retrievable and does not affect HNSW vectors used during search.' },
        { icon: 'bar-chart', titleJa: '見積もりを比較', titleEn: 'Compare estimates', descJa: '各組み合わせの理論ベクトルサイズ (bytes / GB)、ドキュメント数やクエリ負荷の補助見積もりが表示されます。本番適用前の SKU サイズ設計に使いましょう。', descEn: 'See theoretical vector size (bytes / GB) per combination plus side estimates (doc count, query load). Use it to size SKUs before committing.', targetSelector: '[data-guide-target="vo-estimate"]' },
      ],
      tipsJa: [
        'scalarQuantization (int8) は品質劣化が小さく (多くのモデルで 1–2% 程度の recall 低下)、まずここから始めるのが定石です。さらに binaryQuantization を使う場合は rescoring とセットで使うのが推奨。',
        'truncationDimension (MRL) は text-embedding-3 系モデルで効果的です (単純に次元を切り詰めるだけでは品質が大きく劣化するモデルもあります)。例: 3072 → 1024 でも十分な品質を保てるケースが多いです。',
        '量子化 × MRL を重ねると 32× 以上のサイズ削減も可能ですが、recall 低下を AutoTuning で定量検証してから本番適用しましょう。',
        'ストレージコストだけでなく、サービス SKU のベクトルストレージ上限 (vectorIndexSize quota) も判断軸になります。クォータを超えそうなら、SKUアップより圧縮調整が先。',
        '変更はインデックスを再作成 (or 新規フィールドとして追加) しないと適用されません。本番では Alias 経由のスワップ計画が必須。',
      ],
      tipsEn: [
        'scalarQuantization (int8) keeps quality close (~1–2% recall drop on most models) and is the default starting point. binaryQuantization is recommended together with rescoring.',
        'truncationDimension (MRL) is meaningful for the text-embedding-3 family (other models often degrade if you simply truncate). Many production cases hold quality from 3072 → 1024.',
        'Stacking quantization × MRL can yield 32× or more savings, but always validate recall loss with AutoTuning before going live.',
        'Beyond storage cost, your service’s vectorIndexSize quota matters. If you are near the cap, compression is preferable to a SKU upgrade.',
        'Settings are not retroactive — you must recreate the index (or add as a new field). In production, plan an Alias-based swap.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/vector-search-how-to-quantization',
    },
  },
  {
    id: 'qps-tester',
    icon: 'speedometer2',
    category: 'optimization',
    titleJa: 'QPS Tester',
    titleEn: 'QPS Tester',
    descJa: '5 種の検索モードで QPS・レイテンシ (p50/p95) を計測。キャパシティプランニングに最適。',
    descEn: 'Measure QPS and latency (p50/p95) across 5 search modes. Ideal for capacity planning.',
    action: 'openQpsTester',
    guide: {
      stepsJa: 'QPS Tester の使い方',
      stepsEn: 'How to use QPS Tester',
      steps: [
        { icon: 'pencil-square', titleJa: 'クエリを準備', titleEn: 'Prepare the query', descJa: '事前に Request Builder で本番と同じクエリ設定 (filter / select / top / vectorQueries など) を作ることが重要です。テストはこの設定をそのまま何回も送信します。', descEn: 'First build the production-shaped query (filter / select / top / vectorQueries) in Request Builder. The tester sends that exact query repeatedly.' },
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから QPS Tester を起動。接続中サービスに対して計測が実行されるため、本番と同じ SKU・同じレプリカ数で走らせるのが理想。', descEn: 'Open QPS Tester from the Tools menu. Measurements run against the connected service — ideally use the same SKU and replica count as production.' },
        { icon: 'people', titleJa: '負荷パラメータ', titleEn: 'Load parameters', descJa: '1 モードあたりのリクエスト数と同時実行数 (concurrency) を設定。Search の Replicas スケールと、インデックスサイズに対して現実的な負荷にしましょう。', descEn: 'Set requests-per-mode and concurrency. Pick a load that’s realistic for your replica count and index size.', targetSelector: '[data-guide-target="qps-controls"]' },
        { icon: 'play-circle', titleJa: '走らせる', titleEn: 'Run', descJa: 'Run を押すと 5 モード (query / semantic / vector / hybrid / semantic_hybrid) を順次 (並列実行は各モード内) に計測。進捗と途中結果がリアルタイムで見えます。', descEn: 'Click Run to measure 5 modes (query / semantic / vector / hybrid / semantic_hybrid) sequentially with parallelism per mode. Progress and partial results stream live.', targetSelector: '[data-guide-target="qps-run"]' },
        { icon: 'clipboard-data', titleJa: '結果を読む', titleEn: 'Read the results', descJa: 'QPS、p50 / p95 / max latency、エラー数 (HTTP 503 スロットリング含む) をモード別に確認。Experiment Run として保存されるため、予算・スケールリングの根拠として使えます。', descEn: 'Inspect QPS, p50 / p95 / max latency, and error counts (including HTTP 503 throttling) per mode. Saved as Experiment Runs — useful evidence for budgeting and scaling decisions.' },
      ],
      tipsJa: [
        'サービスは同一クエリを連続で受けるとキャッシュが効いて latency が低く見えがちです。より現実的な計測にはテストクエリを複数パターン用意してローテーションさせると良いです (今後拡張予定)。',
        '503 が出たらレプリカ不足または QPS オーバー。Replicas を増やす × レトライを仕込む × クエリ軽量化 (select の効果大) の 3 軸で対処を検討しましょう。',
        'semantic と semantic_hybrid はリランカー課金の対象になります。負荷テストも課金に入るため件数に注意。',
        'p95 が SLA に入っているか、そして平均よりも p95 / max に強く注目しましょう。テールこそが真実です。',
        '同じ検索クエリでも vectorExhaustive=true や retrievalReasoningEffort=high は一気に重くなります。本番で使う予定の設定で計測しましょう。',
      ],
      tipsEn: [
        'Service caching can artificially lower latency when repeating the same query. For more realistic numbers, parameterize queries (planned enhancement).',
        '503 errors mean replicas are insufficient or you are exceeding QPS budget. Address along three axes: more replicas, retry policy, and lighter queries (select can help a lot).',
        'semantic and semantic_hybrid hit the reranker billing meter — keep volume in mind during load tests.',
        'Care about whether p95 fits the SLA, and inspect the gap between average and p95 / max — that’s where the truth lives.',
        'vectorExhaustive=true and retrievalReasoningEffort=high get heavy fast. Measure with the exact settings you intend to ship.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-performance-optimization',
    },
  },

  // ── Developer Tools / Visualizers ────────────────────────────
  {
    id: 'search-pipeline-visualizer',
    icon: 'bar-chart-steps',
    category: 'devtool',
    titleJa: 'Search Pipeline Visualizer',
    titleEn: 'Search Pipeline Visualizer',
    descJa: '4 段階の検索パイプライン (Text → Vector → Hybrid → Semantic) を並列実行して可視化。',
    descEn: 'Visualize the 4-stage search pipeline (Text → Vector → Hybrid → Semantic) side by side.',
    action: 'openSearchPipelineVisualizer',
    guide: {
      stepsJa: 'Search Pipeline Visualizer の使い方',
      stepsEn: 'How to use Search Pipeline Visualizer',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Search Pipeline Visualizer を起動します。接続中のサービスとインデックスを使います。', descEn: 'Open Search Pipeline Visualizer from the Tools menu. Uses the connected service and selected index.' },
        { icon: 'pencil-square', titleJa: 'クエリとパラメータを入力', titleEn: 'Configure query & params', descJa: 'クエリ文字列、ベクトルフィールド名 (kind/text または事前計算ベクトル)、semanticConfiguration を設定。これらが 4 ステージで共通に使われます。', descEn: 'Set the query text, vector field name (kind/text or precomputed vector), and semanticConfiguration. These are shared across the 4 stages.', targetSelector: '[data-guide-target="spv-query"]' },
        { icon: 'play-circle', titleJa: '並列実行', titleEn: 'Run in parallel', descJa: 'Run を押すと 4 ステージ (Text=BM25, Vector=k-NN, Hybrid=RRF 融合, Semantic Hybrid=リランカー適用) が同時にディスパッチされ、返り順に表示されます。', descEn: 'Click Run to dispatch all four stages (Text=BM25, Vector=k-NN, Hybrid=RRF fusion, Semantic Hybrid=reranked) at once; columns fill in as each completes.', targetSelector: '[data-guide-target="spv-run"]' },
        { icon: 'eye', titleJa: 'ドキュメントを追跡', titleEn: 'Track a document', descJa: '任意のドキュメントをクリックすると 4 ステージでそのドキュメントが何位にいるかハイライトされます。「どのステージで離脱したか」が一目でわかります。', descEn: 'Click any document to highlight its rank in all four stages — you immediately see at which stage it dropped off.' },
        { icon: 'clipboard-data', titleJa: 'スコアを比較', titleEn: 'Compare scores', descJa: '@search.score はステージごとに意味が違います (BM25 / cosine / RRF 融合)。Semantic Hybrid では @search.rerankerScore も同時に見て「リランカーが順位をひっくり返したドキュメント」に注目しましょう。', descEn: '@search.score means different things per stage (BM25 / cosine / RRF). For Semantic Hybrid, also check @search.rerankerScore — the most informative ones are docs whose rank changed dramatically after reranking.' },
      ],
      tipsJa: [
        '「チャンクサイズ/オーバーラップ設計」の検討に有効。Text でヒットしないが Vector でヒットする → チャンクをもっと小さく、逆に Vector でも拾えない → 埋め込みモデル見直しのシグナル。',
        'Hybrid が Text/Vector より明らかに劣るケースはほぼないです。逆転して見えるときは vectorWeightや maxTextRecallSize の設定ミスを疑いましょう。',
        'Semantic Hybrid で順位が大きく動いたドキュメントに、本番 UI の “関連する質問” や “根拠表示” のヒントが隠れています。',
        'クエリはコピーして Request Builder に貼り、そのまま Experiment Run として保存すると、後で同じ事象を見返せます。',
        '同じクエリを 4 ステージセットで 30〜50 件も見れば、「とりあえず Semantic Hybrid が見た目一番」という感覚がつきます。それを定量化したいときは AutoTuning へ。',
      ],
      tipsEn: [
        'Great for chunk size / overlap design: text misses but vector hits → chunks are too small; even vector cannot recover → the embedding model needs reconsideration.',
        'Hybrid is rarely worse than Text or Vector alone. When it is, suspect vectorWeight or maxTextRecallSize misconfiguration.',
        'Documents whose rank shifts most under Semantic Hybrid often hide “related questions” or “grounding evidence” for production UIs.',
        'Copy a query into Request Builder and save it as an Experiment Run to revisit the same incident later.',
        'Run 30–50 queries through the 4 stages and you will quickly feel that “Semantic Hybrid is best by eye”. To quantify, switch to AutoTuning.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/hybrid-search-overview',
    },
  },
  {
    id: 'text-to-vector',
    icon: '123',
    category: 'devtool',
    titleJa: 'Text to Vector',
    titleEn: 'Text to Vector',
    descJa: 'テキストからベクトル埋め込みを生成。次元数の確認とクエリへの貼り付けが可能。',
    descEn: 'Generate vector embeddings from text. Check dimensions and paste into queries.',
    action: 'openTextToVector',
    guide: {
      stepsJa: 'Text to Vector の使い方',
      stepsEn: 'How to use Text to Vector',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Text to Vector モーダルを起動します。', descEn: 'Open the Text to Vector modal from the Tools menu.' },
        { icon: 'gear', titleJa: 'Azure OpenAI の接続', titleEn: 'Azure OpenAI connection', descJa: 'endpoint (https://<resource>.openai.azure.com)、API key (またはマネージド ID 認証)、deployment ID (例: text-embedding-3-large)、api-version を設定。インデックス側の vectorizer と同じデプロイメントを使うのが重要です。', descEn: 'Set endpoint (https://<resource>.openai.azure.com), API key (or managed identity), deployment ID (e.g. text-embedding-3-large), and api-version. Crucially, use the same deployment as the index’s vectorizer.', targetSelector: '[data-guide-target="t2v-endpoint"]' },
        { icon: 'input-cursor-text', titleJa: 'テキストを入力', titleEn: 'Enter text', descJa: 'ベクトル化したいテキストを貼り付けます。クエリ生成だけでなく「スキーマ設計時に代表ドキュメントチャンクをベクトル化してサイズ感を掴む」用途にも便利です。', descEn: 'Paste the text to embed. Beyond query generation, this is also handy for “embed a representative document chunk and inspect dimensions/scale” during schema design.', targetSelector: '[data-guide-target="t2v-input"]' },
        { icon: 'play-circle', titleJa: '生成', titleEn: 'Generate', descJa: 'Generate を押すと POST {endpoint}/openai/deployments/{deployment}/embeddings?api-version=... が送信され、返ってきたベクトルと次元数 (例: 3072) が表示されます。', descEn: 'Generate sends POST {endpoint}/openai/deployments/{deployment}/embeddings?api-version=... and shows the returned vector and dimensionality (e.g. 3072).', targetSelector: '[data-guide-target="t2v-generate"]' },
        { icon: 'clipboard', titleJa: 'コピーして貼り付け', titleEn: 'Copy & paste', descJa: 'クリップボードにコピーし、Request Builder の vectorQueries (kind=vector) の vector フィールドに貼り付けると、事前計算ベクトル検索をそのまま試せます。', descEn: 'Copy to clipboard and paste into Request Builder’s vectorQueries (kind=vector) vector field to test a precomputed-vector search end-to-end.' },
      ],
      tipsJa: [
        '使うモデルと dimensions の対応: text-embedding-3-large=3072, text-embedding-3-small=1536, text-embedding-ada-002=1536。インデックス側の dimensions と一致させることが絶対条件です。',
        'text-embedding-3 系は dimensions パラメータで任意次元への MRL 切り詰めが可能。インデックスと同じ設定を使いましょう (本ツールも deployment フィールド追加予定)。',
        '同じテキストでもモデルや deployment が違うとベクトルは全く別ものになります。インデックス生成時とクエリ時で deployment を揃えてください。',
        'API キーを手入力したくない場合は Azure OpenAI 側でマネージド ID を付与し、Search サービスと同じ ID で認証する設計を推奨。',
        '生成したベクトルを説明文やデバッグログに貼り付けるとトークン量が膨らみやすいため、本番では必要なときに生成してキャッシュする設計が望ましいです。',
      ],
      tipsEn: [
        'Model ↔ dimensions: text-embedding-3-large=3072, text-embedding-3-small=1536, text-embedding-ada-002=1536. Matching the index’s dimensions is non-negotiable.',
        'The text-embedding-3 family supports MRL truncation via the dimensions parameter — keep the same setting between index and query (we plan to add a deployment hint here too).',
        'Same text + different model/deployment = totally different vectors. Always align deployment between indexing time and query time.',
        'To avoid handling raw API keys, prefer managed identity on Azure OpenAI and authenticate the Search service with the same identity.',
        'Embedding generation tends to balloon tokens when copy-pasted into prompts/logs. In production, generate on demand and cache results.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/vector-search-integrated-vectorization',
    },
  },
  {
    id: 'index-inspector',
    icon: 'info-circle',
    category: 'devtool',
    titleJa: 'Index Inspector',
    titleEn: 'Index Inspector',
    descJa: 'インデックスのスキーマ詳細表示。フィールド定義、ベクトル設定、セマンティック構成。',
    descEn: 'View index schema details. Field definitions, vector settings, semantic configurations.',
    action: 'openIndexInspector',
    guide: {
      stepsJa: 'Index Inspector の使い方',
      stepsEn: 'How to use Index Inspector',
      steps: [
        { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'インデックスドロップダウン横の虫眼鏡アイコン、またはこのカードから起動。複数インデックスをタブで同時に開けます。', descEn: 'Click the magnifier icon next to the index dropdown, or open from this card. Multiple indexes can be opened in tabs at once.' },
        { icon: 'eye', titleJa: 'Fields タブ: スキーマ詳細', titleEn: 'Fields tab', descJa: 'フィールドごとの type / key / searchable / filterable / sortable / facetable / retrievable / analyzer / dimensions / vectorSearchProfile を一覧。クエリを書く前に「それ filterable ですか」を確認するだけでトラブルを防げます。', descEn: 'Inspect per-field type / key / searchable / filterable / sortable / facetable / retrievable / analyzer / dimensions / vectorSearchProfile. Verifying “is this field filterable?” before writing a query prevents most issues.' },
        { icon: 'diagram-3', titleJa: 'Vector / Semantic / Profiles', titleEn: 'Vector / Semantic / Profiles', descJa: 'vectorSearch (algorithms / profiles / vectorizers / compressions)、semantic.configurations、scoringProfiles をセクションごとに確認可能。ベクトルフィールドがどのプロファイルに紐付いているかが「クエリが期待通り走らない」原因調査の鍵。', descEn: 'Browse vectorSearch (algorithms / profiles / vectorizers / compressions), semantic.configurations, and scoringProfiles by section. Knowing which profile a vector field is bound to is the key to debugging “queries don’t behave as expected”.' },
        { icon: 'clipboard', titleJa: 'JSON をコピー', titleEn: 'Copy JSON', descJa: '表示中のスキーマを JSON としてクリップボードにコピー。Index Builder へ貼り付けてテンプレート起点にしたり、CI/CD へ反映したりできます。', descEn: 'Copy the displayed schema as JSON to the clipboard. Paste into Index Builder as a template, or feed it into CI/CD.' },
      ],
      tipsJa: [
        '「検索がヒットしない」「フィルターが効かない」「セマンティックが動かない」ときの最初の確認場所。スキーマとクエリのミスマッチが原因であるケースが多いです。',
        'ベクトルフィールドは dimensions / vectorSearchProfile / stored / searchable / retrievable の組み合わせを必ず見ましょう。「返りそうに見えていても retrievable=false」はよくある誤認です。',
        '同じサービス内に類似インデックスがあるときは、Inspector でタブを並べると「検索品質が違う」原因がスキーマ差として見えてきます。',
        'analyzers / tokenizers / charFilters の設定を見て「このフィールドは今どのトークンになるか」を Analyze API で検証するワークフローが典型的。',
      ],
      tipsEn: [
        'First place to look when search misses, filters do not work, or semantic search refuses to behave — schema/query mismatch is by far the most common root cause.',
        'For vector fields, always check the combination of dimensions / vectorSearchProfile / stored / searchable / retrievable. “Looks like it should return… oh, retrievable=false” is a classic mistake.',
        'When similar indexes coexist, opening them as tabs in Inspector exposes schema diffs that often explain quality differences.',
        'A typical workflow: read analyzers / tokenizers / charFilters here, then verify “what does this field actually tokenize to?” via the Analyze API.',
      ],
      docsUrl: 'https://learn.microsoft.com/azure/search/search-what-is-an-index',
    },
  },

  // ── Experiment Management ────────────────────────────────────
  {
    id: 'experiment-management',
    icon: 'journal-bookmark',
    category: 'experiment',
    titleJa: '実験管理',
    titleEn: 'Experiment Management',
    descJa: 'クエリ実行結果を Run として保存。複数 Run の比較表示、ノート記録、エクスポート/インポート。',
    descEn: 'Save query results as Runs. Compare multiple runs side by side, add notes, export/import.',
    action: 'openExperimentManagement',
    guide: {
      stepsJa: '実験管理の使い方',
      stepsEn: 'How to use Experiment Management',
      steps: [
        { icon: 'journal-plus', titleJa: 'Experiment を作成', titleEn: 'Create an Experiment', descJa: '左ペインの + で新規 Experiment を作成。名前とタグ (例: dataset=hr-faq, model=v3-large) を付けておくと、後で Run 一覧をしぼり込みやすくなります。', descEn: 'Create a new Experiment with the + button in the left pane. Tagging it (e.g. dataset=hr-faq, model=v3-large) makes it easier to filter Runs later.' },
        { icon: 'pin-angle', titleJa: 'ピン留めと並べ替え', titleEn: 'Pin & sort', descJa: 'よく使う Experiment はピン留めして上部に固定。検索ボックスでクエリ文字列・タグ・日付で絞り込めます。', descEn: 'Pin frequently-used Experiments to the top. Use the search box to filter by query text, tag, or date.' },
        { icon: 'pencil-square', titleJa: '事前ノート (任意)', titleEn: 'Pre-execution notes (optional)', descJa: '「vectorWeight=2 を試す」「チャンクサイズを変えた後」など、付随ノートを入力してから検索すると、そのノートが Run にそのまま紐付けられます。', descEn: 'Type a side-note (“try vectorWeight=2”, “after chunk size change”, etc.) before executing — it gets attached to the Run as a memo.' },
        { icon: 'play-circle', titleJa: 'クエリを実行', titleEn: 'Execute the query', descJa: 'Request Builder / Agentic / Analyze どのモードでも Execute すると自動でアクティブな Experiment 下に Run が保存されます。リクエスト・レスポンス・タイムスタンプを含みます。', descEn: 'Executing a query in any mode (Request Builder / Agentic / Analyze…) auto-saves a Run under the active Experiment, including request, response, and timestamp.' },
        { icon: 'layout-three-columns', titleJa: 'Run を並べて比較', titleEn: 'Compare Runs side by side', descJa: '複数 Run (最大 10 件) にチェックをつけて並べると、同一クエリに対するドキュメント順位・スコア・レスポンスをカラムで見返せます。チューニングの反復サイクルに最適。', descEn: 'Tick multiple Runs (up to 10) to lay them in columns and compare ranks/scores/responses for the same query — ideal for tuning iteration cycles.' },
        { icon: 'download', titleJa: 'エクスポート / インポート', titleEn: 'Export / Import', descJa: 'Run を JSON にエクスポートして Issue / PR / Slack で共有、受け取った側はインポートして同じ Run をローカルで見返せます。検索不具合の再現ファイルとして使えます。', descEn: 'Export Runs as JSON to share via Issue / PR / Slack; the receiver imports them and replays the same Run locally. Doubles as a reproduction artifact for search incidents.' },
      ],
      tipsJa: [
        'Run はブラウザ (IndexedDB) に保存されます。複数デバイス間で同期したいときは JSON エクスポートで受け渡します。',
        '「BM25 だけ vs hybrid」「量子化前 vs 後」のように A/B したいときは、タグをキーに Experiment を分けて Run を集めると見返しやすいです。',
        'AutoTuning / QPS Tester の出力も Run として保存されます。したがって「チューニングセッションそのもの」をひとつの Experiment に記録できます。',
        'Run 名とノートは未来の自分へのメッセージとしてそのときにまとめておくと、数週間後の「これ何だったっけ」を防げます。',
        '検索不具合のレポートを受けたら「該当 Run をエクスポートして添付してください」とチケットに記載してしまえば、トリアージのコストがほぼゼロになります。',
      ],
      tipsEn: [
        'Runs are stored in the browser (IndexedDB). To sync across devices, export/import JSON.',
        'For A/B comparisons (“BM25-only vs hybrid”, “before vs after quantization”), separate Experiments by tag and gather Runs underneath each.',
        'AutoTuning / QPS Tester outputs are also persisted as Runs — you can record an entire “tuning session” as one Experiment.',
        'Treat Run names and notes as messages to your future self — prevents the “what was this again?” moment weeks later.',
        'When you receive a search incident report, ask the reporter to export the Run JSON — zero triage friction.',
      ],
    },
  },

  // ── Azure AI Search Features (not yet in RAGOps Studio) ──────
  {
    id: 'indexer-management',
    icon: 'arrow-repeat',
    category: 'azure',
    titleJa: 'Indexer 管理',
    titleEn: 'Indexer Management',
    descJa: 'データソースからのインデックス自動作成。スケジュール設定、実行状態の監視。',
    descEn: 'Auto-populate indexes from data sources. Schedule runs and monitor execution status.',
    disabled: true,
  },
  {
    id: 'data-source-management',
    icon: 'hdd-network',
    category: 'azure',
    titleJa: 'Data Source 管理',
    titleEn: 'Data Source Management',
    descJa: 'Azure Blob Storage、SQL Database、Cosmos DB などのデータソース接続の作成と管理。',
    descEn: 'Create and manage data source connections for Azure Blob Storage, SQL Database, Cosmos DB, etc.',
    disabled: true,
  },
  {
    id: 'knowledge-store',
    icon: 'archive',
    category: 'azure',
    titleJa: 'Knowledge Store',
    titleEn: 'Knowledge Store',
    descJa: 'AI エンリッチメントの出力を Azure Storage に永続化するプロジェクションの管理。',
    descEn: 'Manage projections to persist AI enrichment outputs to Azure Storage.',
    disabled: true,
  },
  {
    id: 'debug-sessions',
    icon: 'bug',
    category: 'azure',
    titleJa: 'デバッグセッション',
    titleEn: 'Debug Sessions',
    descJa: 'Azure Portal のデバッグセッション相当。スキルセットの段階的デバッグと出力確認。',
    descEn: 'Equivalent to Azure Portal debug sessions. Step-through skillset debugging with output preview.',
    disabled: true,
  },
  {
    id: 'semantic-configuration-builder',
    icon: 'stars',
    category: 'azure',
    titleJa: 'セマンティック構成ビルダー',
    titleEn: 'Semantic Configuration Builder',
    descJa: 'セマンティック検索のための構成 (title / content / keyword フィールド) を GUI で作成。',
    descEn: 'Build semantic configurations (title / content / keyword fields) via GUI.',
    disabled: true,
  },
  {
    id: 'alias-management',
    icon: 'signpost-split',
    category: 'azure',
    titleJa: 'インデックスエイリアス管理',
    titleEn: 'Index Alias Management',
    descJa: 'インデックスエイリアスの作成・更新・削除。ゼロダウンタイムのインデックス切り替え。',
    descEn: 'Create, update, and delete index aliases. Enable zero-downtime index swaps.',
    disabled: true,
  },
  {
    id: 'search-traffic-analytics',
    icon: 'graph-up',
    category: 'azure',
    titleJa: '検索トラフィック分析',
    titleEn: 'Search Traffic Analytics',
    descJa: 'クリックスルー率、検索クエリパターン、ユーザー行動の分析と可視化。',
    descEn: 'Analyze and visualize click-through rates, search query patterns, and user behavior.',
    disabled: true,
  },
]
