/**
 * Basic-mode guide definitions for Feature Portal cards.
 *
 * The Portal supports two guide detail levels:
 * - `basic`    : short, beginner-friendly walkthroughs (this file).
 * - `advanced` : in-depth guides defined inline on each PortalCard
 *                in `featurePortalCards.ts`.
 *
 * Keys correspond to PortalCard `id`. Cards without a basic entry
 * fall back to the advanced guide.
 */

import type { FeatureGuide } from './featurePortalCards'

export const BASIC_GUIDES: Record<string, FeatureGuide> = {
  'fulltext-search': {
    stepsJa: 'フルテキスト検索の使い方',
    stepsEn: 'How to use Full-Text Search',
    steps: [
      { icon: 'plug', titleJa: '接続設定', titleEn: 'Configure Connection', descJa: '画面上部の接続セクションで Azure AI Search のエンドポイントと API キーを入力します。', descEn: 'Enter your Azure AI Search endpoint and API key in the connection section at the top.', targetSelector: '[data-guide-target="connection-section"]' },
      { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: 'ドロップダウンから検索対象のインデックスを選択します。', descEn: 'Choose the target index from the dropdown.', targetSelector: '[data-guide-target="index-dropdown"]' },
      { icon: 'pencil-square', titleJa: 'クエリ入力', titleEn: 'Enter Query', descJa: 'search フィールドに検索キーワードを入力します。queryType で simple / full を選択できます。', descEn: 'Type your search keywords in the search field. Choose simple or full queryType.', targetSelector: '[data-guide-target="search-query"]' },
      { icon: 'funnel', titleJa: 'フィルター設定 (任意)', titleEn: 'Set Filters (Optional)', descJa: 'filter, orderby, select などのパラメータでクエリを絞り込みます。', descEn: 'Refine your query with filter, orderby, select, and other parameters.', targetSelector: '[data-guide-target="query-type"]' },
      { icon: 'play-circle', titleJa: '検索実行', titleEn: 'Execute Search', descJa: 'Execute ボタンを押して検索を実行します。結果は右ペインに JSON で表示されます。', descEn: 'Click Execute to run the search. Results appear as JSON in the right pane.', targetSelector: '[data-guide-target="execute-button"]' },
    ],
    tipsJa: ['queryType を full にすると Lucene 構文 (ワイルドカード、正規表現) が使えます', 'select パラメータで返却フィールドを限定するとレスポンスが軽量になります'],
    tipsEn: ['Set queryType to full to use Lucene syntax (wildcards, regex)', 'Use the select parameter to limit returned fields for lighter responses'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-query-overview',
  },
  'semantic-search': {
    stepsJa: 'セマンティック検索の使い方',
    stepsEn: 'How to use Semantic Search',
    steps: [
      { icon: 'toggles', titleJa: 'Lab Mode 切替', titleEn: 'Switch Lab Mode', descJa: 'Semantic-Vector モードを選択します（上部のモード切替）。', descEn: 'Select Semantic-Vector mode from the mode switcher at the top.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
      { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: 'セマンティック構成のあるインデックスを選択します。', descEn: 'Select an index that has a semantic configuration.', targetSelector: '[data-guide-target="index-dropdown"]' },
      { icon: 'pencil-square', titleJa: 'クエリ入力', titleEn: 'Enter Query', descJa: '自然言語でクエリを入力します。', descEn: 'Enter a natural language query.', targetSelector: '[data-guide-target="search-query"]' },
      { icon: 'gear', titleJa: 'セマンティック構成', titleEn: 'Semantic Configuration', descJa: 'queryType を semantic に設定し、semanticConfiguration を選択します。', descEn: 'Set queryType to semantic and select a semanticConfiguration.', targetSelector: '[data-guide-target="query-type"]' },
      { icon: 'play-circle', titleJa: '実行 & 確認', titleEn: 'Execute & Review', descJa: 'Execute を押して結果を確認します。@search.rerankerScore でセマンティックスコアを確認できます。', descEn: 'Click Execute and review results. Check @search.rerankerScore for semantic scores.', targetSelector: '[data-guide-target="execute-button"]' },
    ],
    tipsJa: ['セマンティックランカーを使うにはインデックスにセマンティック構成が必要です', 'debug パラメータを semantic に設定するとランキング根拠を確認できます'],
    tipsEn: ['Semantic ranker requires a semantic configuration on the index', 'Set debug parameter to semantic to see ranking rationale'],
    docsUrl: 'https://learn.microsoft.com/azure/search/semantic-search-overview',
  },
  'vector-search': {
    stepsJa: 'ベクトル検索の使い方',
    stepsEn: 'How to use Vector Search',
    steps: [
      { icon: 'toggles', titleJa: 'Semantic-Vector モード', titleEn: 'Semantic-Vector Mode', descJa: 'Semantic-Vector モードに切り替えてベクトルセクションを有効にします。', descEn: 'Switch to Semantic-Vector mode to enable the vector section.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
      { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: 'ベクトルフィールドを持つインデックスを選択します。', descEn: 'Select an index that contains vector fields.', targetSelector: '[data-guide-target="index-dropdown"]' },
      { icon: 'input-cursor-text', titleJa: 'クエリ入力', titleEn: 'Query Input', descJa: 'テキストでクエリを入力します（統合ベクトル化）。', descEn: 'Enter a text query (integrated vectorization).', targetSelector: '[data-guide-target="search-query"]' },
      { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: 'Execute を押してベクトル検索を実行します。', descEn: 'Click Execute to run vector search.', targetSelector: '[data-guide-target="execute-button"]' },
    ],
    tipsJa: ['search フィールドにテキストも入力するとハイブリッド検索になります', 'vectorExhaustive を有効にすると正確な KNN 検索が実行されます（低速）'],
    tipsEn: ['Adding text in the search field enables hybrid search', 'Enable vectorExhaustive for exact KNN search (slower)'],
    docsUrl: 'https://learn.microsoft.com/azure/search/vector-search-overview',
  },
  'hybrid-search': {
    stepsJa: 'ハイブリッド検索の使い方',
    stepsEn: 'How to use Hybrid Search',
    steps: [
      { icon: 'toggles', titleJa: 'モード設定', titleEn: 'Set Mode', descJa: 'Semantic-Vector モードで、search フィールドにテキスト、ベクトルセクションも有効にします。', descEn: 'In Semantic-Vector mode, enter text in search and enable the vector section.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
      { icon: 'pencil-square', titleJa: 'クエリ入力', titleEn: 'Enter Query', descJa: 'search フィールドにテキストを入力します（ベクトルと統合されます）。', descEn: 'Enter text in the search field (combined with vector query).', targetSelector: '[data-guide-target="search-query"]' },
      { icon: 'play-circle', titleJa: '実行 & 比較', titleEn: 'Execute & Compare', descJa: '実行後、@search.score (RRF 融合スコア) を確認します。All Modes で全モード同時実行も可能。', descEn: 'After execution, check @search.score (RRF fusion score). Use All Modes to run all modes at once.', targetSelector: '[data-guide-target="execute-button"]' },
    ],
    tipsJa: ['vectorWeight=0.5 が一般的な出発点です', 'All Modes 実行で text / vector / hybrid / semantic_hybrid を一括比較できます'],
    tipsEn: ['vectorWeight=0.5 is a good starting point', 'Use All Modes to compare text / vector / hybrid / semantic_hybrid at once'],
    docsUrl: 'https://learn.microsoft.com/azure/search/hybrid-search-overview',
  },
  'agentic-retrieval': {
    stepsJa: 'Agentic Retrieval の使い方',
    stepsEn: 'How to use Agentic Retrieval',
    steps: [
      { icon: 'toggles', titleJa: 'Agentic モード', titleEn: 'Agentic Mode', descJa: 'Lab Mode を Agentic に切り替えます。API バージョンは自動的に preview に設定されます。', descEn: 'Switch Lab Mode to Agentic. API version is automatically set to preview.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
      { icon: 'database', titleJa: 'Knowledge Base 選択', titleEn: 'Select Knowledge Base', descJa: 'ドロップダウンから使用する Knowledge Base を選択します。', descEn: 'Choose the Knowledge Base to use from the dropdown.', targetSelector: '[data-guide-target="knowledge-base-dropdown"]' },
      { icon: 'pencil-square', titleJa: 'クエリ入力', titleEn: 'Enter Query', descJa: '自然言語で質問を入力します。エージェントが最適なソースを自動選択して検索します。', descEn: 'Enter your question in natural language. The agent automatically selects optimal sources.', targetSelector: '[data-guide-target="agentic-messages"]' },
      { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: 'Execute を押してエージェント検索を実行します。', descEn: 'Click Execute to run agentic retrieval.', targetSelector: '[data-guide-target="execute-button"]' },
    ],
    tipsJa: ['Knowledge Base は事前に Knowledge Base Builder で作成しておく必要があります', 'retrievalReasoningEffort で推論の深さを調整できます'],
    tipsEn: ['Knowledge Base must be created in advance using Knowledge Base Builder', 'Adjust reasoning depth with retrievalReasoningEffort'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-agentic-retrieval-concept',
  },
  'analyze-api': {
    stepsJa: 'テキスト分析の使い方',
    stepsEn: 'How to use Text Analysis',
    steps: [
      { icon: 'toggles', titleJa: 'Analyze モード', titleEn: 'Analyze Mode', descJa: 'Lab Mode を Analyze に切り替えます。', descEn: 'Switch Lab Mode to Analyze.', targetSelector: '[data-guide-target="lab-mode-switcher"]' },
      { icon: 'list-ul', titleJa: 'インデックス選択', titleEn: 'Select Index', descJa: '分析対象のインデックスを選択します。', descEn: 'Select the target index for analysis.', targetSelector: '[data-guide-target="index-dropdown"]' },
      { icon: 'input-cursor-text', titleJa: 'テキスト入力', titleEn: 'Enter Text', descJa: '分析したいテキストを text フィールドに入力します。', descEn: 'Enter the text you want to analyze in the text field.', targetSelector: '[data-guide-target="analyze-text"]' },
      { icon: 'gear', titleJa: 'アナライザー選択', titleEn: 'Select Analyzer', descJa: 'analyzerName でアナライザーを選択するか、tokenizer + filters の組み合わせを指定します。', descEn: 'Choose an analyzer by analyzerName, or specify a tokenizer + filters combination.', targetSelector: '[data-guide-target="analyze-analyzer"]' },
      { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: '実行するとテキストがトークンに分割された結果が表示されます。', descEn: 'Execute to see how the text is split into tokens.', targetSelector: '[data-guide-target="execute-button"]' },
    ],
    tipsJa: ['日本語には ja.lucene や ja.microsoft アナライザーが適しています', 'カスタムアナライザーはインデックス定義の analyzers セクションで作成できます'],
    tipsEn: ['For Japanese text, ja.lucene or ja.microsoft analyzers work well', 'Custom analyzers are defined in the analyzers section of the index definition'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-analyzers',
  },
  'index-builder': {
    stepsJa: 'Index Builder の使い方',
    stepsEn: 'How to use Index Builder',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューまたはこのカードから Index Builder を開きます。', descEn: 'Open Index Builder from the Tools menu or this card.' },
      { icon: 'list-ul', titleJa: 'インデックス一覧', titleEn: 'Index List', descJa: '接続先サービスの全インデックスが一覧表示されます。選択して詳細を確認できます。', descEn: 'All indexes from the connected service are listed. Select one to view details.', targetSelector: '[data-guide-target="index-builder-list"]' },
      { icon: 'code-slash', titleJa: 'JSON 編集', titleEn: 'Edit JSON', descJa: 'JSON エディタでインデックス定義を編集します。フィールド、ベクトル設定、セマンティック構成を定義します。', descEn: 'Edit index definitions in the JSON editor. Define fields, vector settings, and semantic configs.', targetSelector: '[data-guide-target="index-builder-editor"]' },
      { icon: 'cloud-upload', titleJa: '作成 / 更新', titleEn: 'Create / Update', descJa: 'Create で新規作成、Update で既存インデックスを更新します。', descEn: 'Use Create for new indexes, Update for existing ones.', targetSelector: '[data-guide-target="index-builder-actions"]' },
    ],
    tipsJa: ['JSON ファイルからインポートして既存の定義をベースに編集できます', '統計情報 (documentCount, storageSize) でインデックスの状態を確認できます'],
    tipsEn: ['Import from JSON files to edit based on existing definitions', 'Check index status via statistics (documentCount, storageSize)'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-how-to-create-search-index',
  },
  'synonym-map-builder': {
    stepsJa: 'Synonym Map Builder の使い方',
    stepsEn: 'How to use Synonym Map Builder',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Synonym Map Builder を開きます。', descEn: 'Open Synonym Map Builder from the Tools menu.' },
      { icon: 'list-ul', titleJa: '既存マップ選択', titleEn: 'Select Existing Map', descJa: '既存のシノニムマップを選択するか、新規作成します。', descEn: 'Select an existing synonym map or create a new one.', targetSelector: '[data-guide-target="synonym-map-list"]' },
      { icon: 'pencil-square', titleJa: 'ルール編集', titleEn: 'Edit Rules', descJa: '同義語ルールを追加します。カンマ区切り (等価) または => 記法 (明示的マッピング) で記述します。', descEn: 'Add synonym rules. Use comma-separated (equivalency) or => notation (explicit mapping).', targetSelector: '[data-guide-target="synonym-map-editor"]' },
      { icon: 'cloud-upload', titleJa: '保存', titleEn: 'Save', descJa: 'Azure に公開してシノニムマップを保存します。', descEn: 'Publish to Azure to save the synonym map.', targetSelector: '[data-guide-target="synonym-map-actions"]' },
    ],
    tipsJa: ['等価例: laptop, notebook, portable computer', '明示的マッピング例: USA, U.S.A. => United States'],
    tipsEn: ['Equivalency example: laptop, notebook, portable computer', 'Explicit mapping example: USA, U.S.A. => United States'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-synonyms',
  },
  'knowledge-source-builder': {
    stepsJa: 'Knowledge Source Builder の使い方',
    stepsEn: 'How to use Knowledge Source Builder',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Knowledge Source Builder を開きます。', descEn: 'Open Knowledge Source Builder from the Tools menu.' },
      { icon: 'plus-circle', titleJa: '新規作成', titleEn: 'Create New', descJa: 'ソース名、検索インデックス名、セマンティック構成名を指定して作成します。', descEn: 'Specify source name, search index name, and semantic configuration name to create.', targetSelector: '[data-guide-target="knowledge-source-form"]' },
      { icon: 'gear', titleJa: 'フィールド設定', titleEn: 'Configure Fields', descJa: 'sourceDataFields と searchFields を設定してデータとクエリのマッピングを定義します。', descEn: 'Set sourceDataFields and searchFields to define data and query mappings.', targetSelector: '[data-guide-target="knowledge-source-fields"]' },
      { icon: 'cloud-upload', titleJa: '保存', titleEn: 'Save', descJa: 'Azure に公開します。作成後は Knowledge Base Builder から参照できます。', descEn: 'Publish to Azure. After creation, it can be referenced from Knowledge Base Builder.', targetSelector: '[data-guide-target="knowledge-source-actions"]' },
    ],
    tipsJa: ['Knowledge Source は Knowledge Base の構成要素です。先に作成してからKnowledge Base に追加します'],
    tipsEn: ['Knowledge Sources are building blocks of Knowledge Bases. Create them first, then add to a Knowledge Base'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-agentic-retrieval-how-to-create',
  },
  'knowledge-base-builder': {
    stepsJa: 'Knowledge Base Builder の使い方',
    stepsEn: 'How to use Knowledge Base Builder',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Knowledge Base Builder を開きます。', descEn: 'Open Knowledge Base Builder from the Tools menu.' },
      { icon: 'plus-circle', titleJa: '新規作成', titleEn: 'Create New', descJa: 'ナレッジベース名と説明を入力します。', descEn: 'Enter knowledge base name and description.', targetSelector: '[data-guide-target="knowledge-base-form"]' },
      { icon: 'collection', titleJa: 'ソース追加', titleEn: 'Add Sources', descJa: '事前に作成した Knowledge Source を knowledgeSources 配列に追加します。', descEn: 'Add previously created Knowledge Sources to the knowledgeSources array.', targetSelector: '[data-guide-target="knowledge-base-sources"]' },
      { icon: 'cloud-upload', titleJa: '保存', titleEn: 'Save', descJa: 'Azure に公開します。作成後は Agentic モードで利用できます。', descEn: 'Publish to Azure. After creation, use it in Agentic mode.', targetSelector: '[data-guide-target="knowledge-base-actions"]' },
    ],
    tipsJa: ['1つの Knowledge Base に複数の Knowledge Source を束ねることで、エージェントが最適なソースを自動選択します'],
    tipsEn: ['Bundling multiple Knowledge Sources in one Knowledge Base lets the agent automatically select the best source'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-agentic-retrieval-how-to-create',
  },
  'skill-pipeline-builder': {
    stepsJa: 'Skill Pipeline Builder の使い方',
    stepsEn: 'How to use Skill Pipeline Builder',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Skill Pipeline Builder を開きます。', descEn: 'Open Skill Pipeline Builder from the Tools menu.' },
      { icon: 'plus-circle', titleJa: 'スキル追加', titleEn: 'Add Skills', descJa: 'ツールバーから15 種の組み込みスキルテンプレートを選択してノードを追加します。', descEn: 'Choose from 15 built-in skill templates from the toolbar to add nodes.', targetSelector: '[data-guide-target="spb-toolbar"]' },
      { icon: 'link-45deg', titleJa: '接続', titleEn: 'Connect', descJa: 'キャンバス上のノードのポートをドラッグして入出力を接続します。エンリッチメントパスが自動設定されます。', descEn: 'Drag node ports on the canvas to connect inputs/outputs. Enrichment paths are auto-configured.', targetSelector: '[data-guide-target="spb-canvas"]' },
      { icon: 'code-slash', titleJa: 'JSON 編集', titleEn: 'Edit JSON', descJa: 'Skillset JSON タブでスキルセット全体の JSON を直接編集できます。', descEn: 'Use the Skillset JSON tab to edit the full skillset JSON directly.', targetSelector: '[data-guide-target="spb-tab-skillsetJson"]' },
      { icon: 'bug', titleJa: 'デバッグ', titleEn: 'Debug', descJa: 'Debug Runner タブで実データを使ってスキル出力をプレビューできます。', descEn: 'Use the Debug Runner tab to preview skill outputs with real data.', targetSelector: '[data-guide-target="spb-tab-debugRunner"]' },
      { icon: 'cloud-upload', titleJa: '公開', titleEn: 'Publish', descJa: 'Diff 確認付きで Azure にスキルセットを公開します。', descEn: 'Publish skillsets to Azure with diff confirmation.', targetSelector: '[data-guide-target="spb-publish"]' },
    ],
    tipsJa: ['キャンバスを右クリックすると Indexer / Index の読み込みメニューが表示されます', 'ローカル保存で複数のパイプライン構成を保持できます'],
    tipsEn: ['Right-click the canvas to load Indexer / Index from the menu', 'Use local save to maintain multiple pipeline configurations'],
    docsUrl: 'https://learn.microsoft.com/azure/search/cognitive-search-defining-skillset',
  },
  'skill-code-editor': {
    stepsJa: 'Custom Skill LiveEditor の使い方',
    stepsEn: 'How to use Custom Skill LiveEditor',
    steps: [
      { icon: 'code-slash', titleJa: 'Code タブ', titleEn: 'Code Tab', descJa: 'Code タブに切り替えて Python コードを記述します。def process(input: dict) -> dict の契約に従います。', descEn: 'Switch to the Code tab and write Python code following the def process(input: dict) -> dict contract.', targetSelector: '[data-guide-target="sce-tab-code"]' },
      { icon: 'terminal', titleJa: 'Test タブ', titleEn: 'Test Tab', descJa: 'Test タブで入力 JSON を編集して Local Run (Pyodide) または Remote Run で実行します。', descEn: 'In the Test tab, edit test input JSON and run with Local Run (Pyodide) or Remote Run.', targetSelector: '[data-guide-target="sce-tab-test"]' },
      { icon: 'gear', titleJa: 'Settings タブ', titleEn: 'Settings Tab', descJa: 'Settings タブでランタイム URL の設定、ヘルスチェック、スキルのアップロードを行います。', descEn: 'In the Settings tab, configure runtime URL, health check, and skill upload.', targetSelector: '[data-guide-target="sce-tab-settings"]' },
      { icon: 'cloud-upload', titleJa: 'デプロイ', titleEn: 'Deploy', descJa: 'Blob Storage にコードをアップロードし、Azure Container Apps のランタイムに反映します。', descEn: 'Upload code to Blob Storage and deploy to Azure Container Apps runtime.', targetSelector: '[data-guide-target="sce-tab-settings"]' },
    ],
    tipsJa: ['Local Run は Pyodide (WebAssembly) で動作するため、サーバー不要で即座にテストできます', 'Skill Pipeline Builder からスキルノードを選択して直接開くこともできます'],
    tipsEn: ['Local Run uses Pyodide (WebAssembly) so you can test instantly without a server', 'You can also open directly from a skill node in the Skill Pipeline Builder'],
    docsUrl: 'https://learn.microsoft.com/azure/search/cognitive-search-custom-skill-web-api',
  },
  'filter-builder': {
    stepsJa: 'Filter Builder の使い方',
    stepsEn: 'How to use Filter Builder',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'Request Builder の filter フィールド横のボタンから Filter Builder を開きます。', descEn: 'Open Filter Builder from the button next to the filter field in Request Builder.' },
      { icon: 'plus-circle', titleJa: '条件追加', titleEn: 'Add Condition', descJa: 'フィールド名、演算子 (eq, ne, gt, ge, lt, le, search.in 等)、値を指定して条件を追加します。', descEn: 'Add conditions by specifying field name, operator (eq, ne, gt, ge, lt, le, search.in, etc.), and value.' },
      { icon: 'diagram-3', titleJa: 'ロジック結合', titleEn: 'Combine Logic', descJa: '複数の条件を AND / OR で結合します。', descEn: 'Combine multiple conditions with AND / OR logic.' },
      { icon: 'check2-circle', titleJa: '適用', titleEn: 'Apply', descJa: '生成されたフィルター式をプレビューして、Request Builder に適用します。', descEn: 'Preview the generated filter expression and apply it to the Request Builder.' },
    ],
    tipsJa: ['OData フィルター構文: field eq value, search.in(field, \'a,b,c\') など', 'Filterable に設定されたフィールドのみフィルター可能です'],
    tipsEn: ['OData filter syntax: field eq value, search.in(field, \'a,b,c\'), etc.', 'Only fields marked as Filterable can be filtered'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-filters',
  },
  'auto-tuning': {
    stepsJa: 'AutoTuning の使い方',
    stepsEn: 'How to use AutoTuning',
    steps: [
      { icon: 'file-earmark-arrow-up', titleJa: 'データセット準備', titleEn: 'Prepare Dataset', descJa: 'JSONL 形式の評価データセットを準備します。各行に query (検索クエリ) と expected_ids (正解ドキュメントID) を含めます。', descEn: 'Prepare a JSONL evaluation dataset. Each line should contain query (search query) and expected_ids (ground truth document IDs).', targetSelector: '[data-guide-target="autotuning-upload"]' },
      { icon: 'sliders', titleJa: 'パラメータ空間設定', titleEn: 'Set Parameter Space', descJa: '最適化するパラメータ (インデックス、vectorWeight、vectorK、queryType 等) と探索範囲を設定します。', descEn: 'Configure parameters to optimize (index, vectorWeight, vectorK, queryType, etc.) and their search ranges.', targetSelector: '[data-guide-target="autotuning-params"]' },
      { icon: 'bullseye', titleJa: '評価指標選択', titleEn: 'Select Metric', descJa: '最適化目標 (Precision@k, Recall@k, NDCG, MRR) と k 値を設定します。', descEn: 'Set the optimization objective (Precision@k, Recall@k, NDCG, MRR) and k value.', targetSelector: '[data-guide-target="autotuning-metric"]' },
      { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: 'Run をクリックしてグリッドサーチを開始します。進捗はリアルタイムで表示されます。', descEn: 'Click Run to start the grid search. Progress is displayed in real-time.', targetSelector: '[data-guide-target="autotuning-run"]' },
    ],
    tipsJa: ['samples/ ディレクトリにサンプル JSONL データセットがあります', '結果は Experiment Run として保存され、後から復元・比較できます'],
    tipsEn: ['Sample JSONL datasets are available in the samples/ directory', 'Results are saved as Experiment Runs and can be restored and compared later'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-query-overview',
  },
  'vector-optimizer': {
    stepsJa: 'Vector Optimizer の使い方',
    stepsEn: 'How to use Vector Optimizer',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Vector Optimizer を開きます。', descEn: 'Open Vector Optimizer from the Tools menu.' },
      { icon: 'sliders', titleJa: 'ベクトル設定', titleEn: 'Vector Settings', descJa: 'ベクトル次元数、入力フォーマット (float32/float16) を設定します。', descEn: 'Set vector dimensions and input format (float32/float16).', targetSelector: '[data-guide-target="vo-dimensions"]' },
      { icon: 'gear', titleJa: '最適化オプション', titleEn: 'Optimization Options', descJa: '量子化 (scalar/binary)、truncationDimension、stored、rescoring の組み合わせを設定します。', descEn: 'Configure combinations of quantization (scalar/binary), truncationDimension, stored, and rescoring.', targetSelector: '[data-guide-target="vo-settings"]' },
      { icon: 'bar-chart', titleJa: 'サイズ比較', titleEn: 'Compare Sizes', descJa: '各設定の理論サイズ (バイト数) が自動計算されて比較表示されます。', descEn: 'Theoretical sizes (bytes) are automatically calculated and compared.', targetSelector: '[data-guide-target="vo-estimate"]' },
    ],
    tipsJa: ['scalarQuantization (int8) でメモリ使用量を約 75% 削減できます', 'MRL (truncationDimension) と量子化の併用でさらにサイズを縮小できます'],
    tipsEn: ['scalarQuantization (int8) can reduce memory usage by about 75%', 'Combining MRL (truncationDimension) with quantization further reduces size'],
    docsUrl: 'https://learn.microsoft.com/azure/search/vector-search-how-to-quantization',
  },
  'qps-tester': {
    stepsJa: 'QPS Tester の使い方',
    stepsEn: 'How to use QPS Tester',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから QPS Tester を開きます。', descEn: 'Open QPS Tester from the Tools menu.' },
      { icon: 'pencil-square', titleJa: 'クエリ設定', titleEn: 'Configure Query', descJa: 'Request Builder の現在のクエリ設定がテストに使用されます。事前にクエリを設定してください。', descEn: 'The current query settings from Request Builder are used for testing. Set up your query beforehand.' },
      { icon: 'people', titleJa: '同時実行数', titleEn: 'Concurrency', descJa: 'リクエスト数と同時実行リクエスト数を設定します。', descEn: 'Set the requests per mode and concurrency.', targetSelector: '[data-guide-target="qps-controls"]' },
      { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: '5 種の検索モード (query, semantic, vector, hybrid, semantic_hybrid) で計測を開始します。', descEn: 'Start measurement across 5 search modes (query, semantic, vector, hybrid, semantic_hybrid).', targetSelector: '[data-guide-target="qps-run"]' },
      { icon: 'clipboard-data', titleJa: '結果確認', titleEn: 'Review Results', descJa: 'QPS、p50/p95 レイテンシ、エラー数を確認します。結果は Experiment Run として保存されます。', descEn: 'Check QPS, p50/p95 latency, and error counts. Results are saved as Experiment Runs.' },
    ],
    tipsJa: ['本番環境と同じ SKU・レプリカ数で計測すると正確な結果が得られます', 'p95 レイテンシが SLA 以下であることを確認しましょう'],
    tipsEn: ['Measure with the same SKU and replica count as production for accurate results', 'Verify that p95 latency is within your SLA targets'],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-performance-optimization',
  },
  'search-pipeline-visualizer': {
    stepsJa: 'Search Pipeline Visualizer の使い方',
    stepsEn: 'How to use Search Pipeline Visualizer',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Search Pipeline Visualizer を開きます。', descEn: 'Open Search Pipeline Visualizer from the Tools menu.' },
      { icon: 'pencil-square', titleJa: 'クエリ入力', titleEn: 'Enter Query', descJa: '検索クエリを入力し、ベクトルフィールドとセマンティック構成を設定します。', descEn: 'Enter a search query and configure vector fields and semantic configuration.', targetSelector: '[data-guide-target="spv-query"]' },
      { icon: 'play-circle', titleJa: '実行', titleEn: 'Execute', descJa: '4 つの検索ステージ (Text, Vector, Hybrid, Semantic Hybrid) が並列実行されます。', descEn: 'Four search stages (Text, Vector, Hybrid, Semantic Hybrid) run in parallel.', targetSelector: '[data-guide-target="spv-run"]' },
      { icon: 'eye', titleJa: '結果比較', titleEn: 'Compare Results', descJa: '各ステージの結果を並べて比較します。ドキュメントをクリックすると各ステージでの順位が強調表示されます。', descEn: 'Compare results side by side. Click a document to highlight its rank across all stages.' },
    ],
    tipsJa: ['関連ドキュメントがどのステージで脱落するか確認するのに最適です', 'セマンティックリランキングの効果を直感的に把握できます'],
    tipsEn: ['Great for identifying which stage drops relevant documents', 'Intuitively understand the impact of semantic reranking'],
    docsUrl: 'https://learn.microsoft.com/azure/search/hybrid-search-overview',
  },
  'text-to-vector': {
    stepsJa: 'Text to Vector の使い方',
    stepsEn: 'How to use Text to Vector',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'ツールメニューから Text to Vector を開きます。', descEn: 'Open Text to Vector from the Tools menu.' },
      { icon: 'gear', titleJa: 'エンドポイント設定', titleEn: 'Configure Endpoint', descJa: 'Azure OpenAI のエンドポイント、API キー、モデル名を入力します。', descEn: 'Enter your Azure OpenAI endpoint, API key, and model name.', targetSelector: '[data-guide-target="t2v-endpoint"]' },
      { icon: 'input-cursor-text', titleJa: 'テキスト入力', titleEn: 'Enter Text', descJa: '埋め込みに変換したいテキストを入力します。', descEn: 'Enter the text you want to convert to embeddings.', targetSelector: '[data-guide-target="t2v-input"]' },
      { icon: 'play-circle', titleJa: '生成', titleEn: 'Generate', descJa: 'Generate をクリックしてベクトルを生成します。次元数も表示されます。', descEn: 'Click Generate to create the vector. Dimensions are also displayed.', targetSelector: '[data-guide-target="t2v-generate"]' },
      { icon: 'clipboard', titleJa: 'コピー & 貼り付け', titleEn: 'Copy & Paste', descJa: '生成されたベクトルをコピーして、Request Builder のベクトルクエリに貼り付けます。', descEn: 'Copy the generated vector and paste it into the vector query in Request Builder.' },
    ],
    tipsJa: ['text-embedding-ada-002 は 1536 次元、text-embedding-3-small は 1536 次元（MRL で削減可能）です'],
    tipsEn: ['text-embedding-ada-002 is 1536 dimensions, text-embedding-3-small is 1536 dimensions (reducible via MRL)'],
    docsUrl: 'https://learn.microsoft.com/azure/search/vector-search-integrated-vectorization',
  },
  'index-inspector': {
    stepsJa: 'Index Inspector の使い方',
    stepsEn: 'How to use Index Inspector',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: '開く', titleEn: 'Open', descJa: 'インデックス名の横にある虫眼鏡アイコンをクリックするか、このカードから開きます。', descEn: 'Click the magnifier icon next to the index name, or open from this card.' },
      { icon: 'eye', titleJa: 'スキーマ確認', titleEn: 'View Schema', descJa: 'フィールド定義、ベクトルプロファイル、セマンティック構成が一覧表示されます。', descEn: 'Field definitions, vector profiles, and semantic configurations are displayed.' },
      { icon: 'clipboard', titleJa: 'コピー', titleEn: 'Copy', descJa: 'インデックス定義 JSON をクリップボードにコピーして再利用できます。', descEn: 'Copy the index definition JSON to clipboard for reuse.' },
    ],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-what-is-an-index',
  },
  'index-cluster-visualizer': {
    stepsJa: 'Index Cluster Visualizer の使い方',
    stepsEn: 'How to use Index Cluster Visualizer',
    steps: [
      { icon: 'box-arrow-in-right', titleJa: 'ツールメニューから開く', titleEn: 'Open from Tools menu', descJa: 'ツールメニューから Index Cluster Visualizer を開きます。', descEn: 'Open Index Cluster Visualizer from the Tools menu.' },
      { icon: 'gear', titleJa: 'インデックスとクラスタ数を設定', titleEn: 'Set index & cluster count', descJa: 'インデックス名、ベクトルフィールド、クラスタ数 (k)、最大ドキュメント数を設定します。', descEn: 'Set the index name, vector field, cluster count (k), and max documents.', targetSelector: '[data-guide-target="iv-settings"]' },
      { icon: 'play-circle', titleJa: 'スキャンして散布図を生成', titleEn: 'Scan & generate scatter plot', descJa: '実行ボタンでベクトルスキャン → クラスタリング → 散布図描画が進行します。', descEn: 'Click Run to start vector scan → clustering → scatter plot rendering.', targetSelector: '[data-guide-target="iv-run"]' },
      { icon: 'eye', titleJa: 'クラスタ内ドキュメントを閲覧', titleEn: 'Browse cluster documents', descJa: '散布図のクラスタをホバーまたはクリックしてドキュメントを確認できます。', descEn: 'Hover or click clusters on the scatter plot to view documents.' },
      { icon: 'chat-left-text', titleJa: 'LLM でクラスタを要約して登録', titleEn: 'Summarize & register with LLM', descJa: 'LLM でクラスタ要約を生成し、メタインデックスとして Azure AI Search に登録します。', descEn: 'Generate cluster summaries with LLM and register as a meta-index in Azure AI Search.', targetSelector: '[data-guide-target="iv-meta"]' },
    ],
    tipsJa: ['まず 500〜1000 件で実行して傾向を掴みましょう', 'チャンクインデックスでは Adaptive Sampling を有効に'],
    tipsEn: ['Start with 500–1000 documents to get a feel', 'Enable Adaptive Sampling for chunk indexes'],
    docsUrl: 'https://learn.microsoft.com/azure/search/vector-search-overview',
  },
  'experiment-management': {
    stepsJa: '実験管理の使い方',
    stepsEn: 'How to use Experiment Management',
    steps: [
      { icon: 'journal-plus', titleJa: 'Experiment 作成', titleEn: 'Create Experiment', descJa: '左ペインの + ボタンで新しい Experiment を作成します。名前とタグで整理できます。', descEn: 'Create a new Experiment with the + button in the left pane. Organize with names and tags.' },
      { icon: 'play-circle', titleJa: 'クエリ実行', titleEn: 'Execute Query', descJa: 'Request Builder で検索を実行すると、結果が自動的に Run として保存されます。', descEn: 'Execute a search from Request Builder and results are automatically saved as a Run.' },
      { icon: 'journal-text', titleJa: 'ノート記録', titleEn: 'Add Notes', descJa: '実行前にノートを記録しておくと、Run にメモとして紐付けられます。', descEn: 'Record notes before execution to attach them as memos to the Run.' },
      { icon: 'layout-three-columns', titleJa: 'Run 比較', titleEn: 'Compare Runs', descJa: '左ペインで複数の Run を選択すると、結果を並べて比較できます（最大 10 件）。', descEn: 'Select multiple Runs in the left pane to compare results side by side (up to 10).' },
      { icon: 'download', titleJa: 'エクスポート', titleEn: 'Export', descJa: 'Run をJSON 形式でエクスポートし、別環境でインポートして共有できます。', descEn: 'Export Runs in JSON format and import in another environment to share.' },
    ],
    tipsJa: ['pinned Experiment はリスト上部に固定表示されます', 'Run のクエリテキストでフィルタリングして素早く目的の Run を見つけられます'],
    tipsEn: ['Pinned Experiments stay at the top of the list', 'Filter Runs by query text to quickly find what you need'],
  },
  'eval-dataset-generator': {
    stepsJa: 'Eval Dataset Generator の使い方',
    stepsEn: 'How to use Eval Dataset Generator',
    steps: [
      { icon: 'list-ul', titleJa: 'インデックスを選ぶ', titleEn: 'Select an index', descJa: 'クエリ生成元となる Azure AI Search インデックスを選択します。Connection 設定で endpoint・API key・key field が解決済みである必要があります。', descEn: 'Choose the Azure AI Search index that will source the documents. The Connection panel must already have endpoint, API key, and key field resolved.', targetSelector: '[data-guide-target="edg-index"]' },
      { icon: 'sliders', titleJa: 'サンプル件数とクエリ数を決める', titleEn: 'Set sample size & queries per doc', descJa: 'sampleSize (インデックスから取り出すドキュメント数) と queriesPerDoc (1 ドキュメントあたりの生成クエリ数) を設定します。総生成クエリ数 = sampleSize × queriesPerDoc が LLM 呼び出し回数の目安です。', descEn: 'Configure sampleSize (documents to draw from the index) and queriesPerDoc (queries to synthesize per document). Total queries = sampleSize × queriesPerDoc, which is roughly the number of LLM calls.', targetSelector: '[data-guide-target="edg-sample-size"]' },
      { icon: 'cloud-fill', titleJa: 'Azure OpenAI 接続を確認', titleEn: 'Verify the Azure OpenAI connection', descJa: 'Chat デプロイ (gpt-4o 等) を設定し、必要に応じて Embeddings デプロイも設定します。Embeddings は Semantic dedup などの埋め込みベース機能で必要ですが、Hard Negative Mining には不要です。', descEn: 'Configure the chat deployment (e.g. gpt-4o) and, if needed, the embeddings deployment. Embeddings are required for semantic dedup and other embedding-based features, but not for hard negative mining.', targetSelector: '[data-guide-target="edg-embedding-deployment"]' },
      { icon: 'play-circle', titleJa: '生成を実行する', titleEn: 'Run generation', descJa: 'Generate を押すと、ドキュメントのサンプリング → 本文の 4000 字切り詰め → LLM によるクエリ生成 → 品質フィルタの順でパイプラインが進行します。進捗バーで現在のステップを確認できます。', descEn: 'Press Generate. The pipeline runs: document sampling → body truncation to 4000 chars → LLM query generation → quality filters. The progress bar shows the current step.', targetSelector: '[data-guide-target="edg-generate"]' },
      { icon: 'clipboard-data', titleJa: '結果を確認して保存する', titleEn: 'Review & save results', descJa: '生成された各クエリの query / expected_ids / query_type / language を一覧で確認し、必要に応じて手動で編集します。Save にタイトルを付けて保存すると、ブラウザの localStorage (key: ragops.evalDatasets.v1) に永続化されます。', descEn: 'Inspect the generated rows (query / expected_ids / query_type / language) and edit any that look off. Saving with a title persists the dataset to browser localStorage (key: ragops.evalDatasets.v1).', targetSelector: '[data-guide-target="edg-persist-save"]' },
      { icon: 'arrow-right-circle', titleJa: 'AutoTuning へ送る', titleEn: 'Send to AutoTuning', descJa: 'Send to AutoTuning を押すと、生成データセットがそのまま AutoTuning タブに引き渡されます。保存済みデータセットは AutoTuning 側のドロップダウンからも再選択できます。', descEn: 'Press “Send to AutoTuning” to hand the dataset off directly. Saved datasets are also reselectable from the AutoTuning dropdown.', targetSelector: '[data-guide-target="edg-send-autotuning"]' },
    ],
    tipsJa: [
      '出力はあくまで「合成評価データセット」です。構成変更の相対比較 (A/B) と回帰検知のために使い、本番品質スコアの代理指標としては扱わないでください。',
      'エクスポートや AutoTuning 投入の前に、必ず人手でクエリと expected_ids をレビューしてください。誤った正解は最適化の方向自体を歪めます。',
      'コスト感の目安: 1 件のクエリ生成は LLM 呼び出し 1 回。Round-trip Consistency や Hard Negative Mining、Entity-KG を ON にすると 1 クエリあたりの LLM/検索呼び出し回数が増えます。',
      '保存先はブラウザの localStorage (`ragops.evalDatasets.v1`) なので、サイトデータを消去するとデータセットも失われます。長期保存用には Export で JSONL をローカルへ書き出してください。',
      'まずは sampleSize と queriesPerDoc を小さく (例: 5 × 2 = 10 件) 設定して動作を確認し、品質と費用感を掴んでから本番規模に拡張するのが安全です。',
    ],
    tipsEn: [
      'Treat the output strictly as a synthetic eval dataset — useful for relative comparison (A/B of configuration changes) and regression detection, not as a proxy for production quality scores.',
      'Always human-review the queries and expected_ids before exporting or feeding into AutoTuning. Bad ground truth biases the entire optimization direction.',
      'Cost rule of thumb: each generated query is one LLM call. Enabling Round-trip Consistency, Hard Negative Mining, or Entity-KG adds extra LLM/search calls per query.',
      'Datasets are stored in browser localStorage (`ragops.evalDatasets.v1`), so clearing site data discards them. For durable storage, export to JSONL locally.',
      'Start small (e.g. sampleSize=5 × queriesPerDoc=2 → 10 queries) to validate quality and cost, then scale up once you have a feel for it.',
    ],
    docsUrl: 'https://learn.microsoft.com/azure/search/search-query-overview',
  },
}
